// Copyright 2025 The Openbot Authors (duyongquan)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package autonomy.tasks.proto;

import "autonomy/commsgs/proto/builtin_interfaces.proto";
import "autonomy/commsgs/proto/geometry_msgs.proto";
import "autonomy/tasks/proto/error_code.proto";

message NavigateThroughPosesAction {
  message Goal {
    repeated autonomy.commsgs.proto.geometry_msgs.PoseStamped poses = 1;
    string behavior_tree = 2;
  }

  message Feedback {
    autonomy.commsgs.proto.geometry_msgs.PoseStamped current_pose = 1;
    autonomy.commsgs.proto.builtin_interfaces.Duration navigation_time = 2;
    autonomy.commsgs.proto.builtin_interfaces.Duration estimated_time_remaining = 3;
    int32 number_of_recoveries = 4;
    float distance_remaining = 5;
    int32 number_of_poses_remaining = 6;
  }

  message Result {
    NavigateThroughPosesErrorCode error_code = 1;
    string error_msg = 2;
  }

  Goal goal = 1;
  Feedback feedback = 2;
  Result result = 3;
}
