load(
    "//tools:package.bzl",
    "autonomy_cc_library",
)

package(default_visibility = ["//visibility:public"])

genrule(
    name = "generate_config",
    srcs = ["config.hpp.cmake"],
    outs = ["config.hpp"],
    cmd = """
sed \
  -e 's|@AUTONOMY_CONFIGURATION_FILES_DIRECTORY@|/tmp/autonomy/conf|g' \
  -e 's|@PROJECT_SOURCE_DIR@|autonomy|g' \
  -e 's|@CMAKE_INSTALL_PREFIX@|/usr/local|g' \
  -e 's|@CMAKE_CURRENT_BINARY_DIR@|bazel-bin|g' \
  $(location config.hpp.cmake) > $@
""",
)

genrule(
    name = "generate_version",
    srcs = [
        "version.cpp.in",
        "//:version.json",
    ],
    outs = ["version_generated.cpp"],
    cmd = "python3 $(location //tools/python:generate_version_cpp.py) $(location version.cpp.in) $(location //:version.json) $@",
    tools = ["//tools/python:generate_version_cpp.py"],
)

autonomy_cc_library(
    name = "autonomy_common",
    srcs = [
        "endian.cpp",
        "file.cpp",
        "fixed_ratio_sampler.cpp",
        "gflags.cpp",
        "json_util.cpp",
        "kalman_filter/kalman_filter.cpp",
        "kalman_filter/time_delay_kalman_filter.cpp",
        "logging.cpp",
        "math/aabox2d.cpp",
        "math/angle.cpp",
        "math/box2d.cpp",
        "math/integral.cpp",
        "math/line_segment2d.cpp",
        "math/math.cpp",
        "math/math_utils.cpp",
        "math/matrix_operations.cpp",
        "math/mpc_osqp.cpp",
        "math/polygon2d.cpp",
        "math/polynomial.cpp",
        "math/random.cpp",
        "math/sin_table.cc",
        "math/vec2d.cpp",
        "motion_model/differential_drive_motion_model.cpp",
        "motion_model/linear_motion_model.cpp",
        "optimization/core/composite.cpp",
        "optimization/core/leaves.cpp",
        "optimization/core/problem.cpp",
        "param_handler.cpp",
        "ply.cpp",
        "signal_filters/signal_filter.cpp",
        "signal_processing/butterworth.cpp",
        "signal_processing/lowpass_filter.cpp",
        "signal_processing/lowpass_filter_1d.cpp",
        "state_estimation/noise_model/uniform_noise.cpp",
        "state_estimation/noise_model/wiener_noise.cpp",
        "state_vector/common_states.cpp",
        "string_util.cpp",
        "task.cpp",
        "thread_pool.cpp",
        "time.cpp",
        "time_util.cpp",
        "transform/rigid_transform.cpp",
        "transform/transform.cpp",
        ":generate_version",
        "network/common/tensor.cpp",
    ],
    hdrs = [
        "blocking_queue.hpp",
        "conf_loader.hpp",
        "configuration_file_resolver.hpp",
        "eigen_alignment.hpp",
        "eigen_defs.hpp",
        "endian.hpp",
        "eventpp/callbacklist.hpp",
        "eventpp/eventdispatcher.hpp",
        "eventpp/eventpolicies.hpp",
        "eventpp/eventqueue.hpp",
        "eventpp/hetercallbacklist.hpp",
        "eventpp/hetereventdispatcher.hpp",
        "eventpp/hetereventqueue.hpp",
        "eventpp/internal/eventpolicies_i.hpp",
        "eventpp/internal/eventqueue_i.hpp",
        "eventpp/internal/hetercallbacklist_i.hpp",
        "eventpp/internal/typeutil_i.hpp",
        "eventpp/mixins/mixinfilter.hpp",
        "eventpp/mixins/mixinheterfilter.hpp",
        "eventpp/utilities/anydata.hpp",
        "eventpp/utilities/anyid.hpp",
        "eventpp/utilities/argumentadapter.hpp",
        "eventpp/utilities/conditionalfunctor.hpp",
        "eventpp/utilities/conditionalremover.hpp",
        "eventpp/utilities/counterremover.hpp",
        "eventpp/utilities/eventmaker.hpp",
        "eventpp/utilities/eventutil.hpp",
        "eventpp/utilities/orderedqueuelist.hpp",
        "eventpp/utilities/scopedremover.hpp",
        "factory.hpp",
        "file.hpp",
        "fixed_ratio_sampler.hpp",
        "function_traits.hpp",
        "future.hpp",
        "gflags.hpp",
        "helper_functions/angle_utils.hpp",
        "helper_functions/bool_comparisons.hpp",
        "helper_functions/byte_reader.hpp",
        "helper_functions/crtp.hpp",
        "helper_functions/float_comparisons.hpp",
        "helper_functions/mahalanobis_distance.hpp",
        "helper_functions/message_adapters.hpp",
        "helper_functions/template_utils.hpp",
        "helper_functions/type_name.hpp",
        "helper_functions/type_traits.hpp",
        "helper_functions/types.hpp",
        "json_util.hpp",
        "kalman_filter/kalman_filter.hpp",
        "kalman_filter/time_delay_kalman_filter.hpp",
        "logging.hpp",
        "lru_cache.hpp",
        "lua.hpp",
        "lua_parameter_dictionary.hpp",
        "macros.hpp",
        "math/aabox2d.hpp",
        "math/aaboxkdtree2d.hpp",
        "math/angle.hpp",
        "math/box2d.hpp",
        "math/curve_fitting.hpp",
        "math/eigen_alignment.hpp",
        "math/euler_angles_zxy.hpp",
        "math/factorial.hpp",
        "math/hermite_spline.hpp",
        "math/integral.hpp",
        "math/line_segment2d.hpp",
        "math/math.hpp",
        "math/math_utils.hpp",
        "math/matrix.hpp",
        "math/matrix_operations.hpp",
        "math/mpc_osqp.hpp",
        "math/polygon2d.hpp",
        "math/polynomial.hpp",
        "math/qp_solver/qp_solver.hpp",
        "math/random.hpp",
        "math/se3.hpp",
        "math/sin_table.hpp",
        "math/so3.hpp",
        "math/vec2d.hpp",
        "message_util.hpp",
        "motion_model/differential_drive_motion_model.hpp",
        "motion_model/linear_motion_model.hpp",
        "motion_model/motion_model_interface.hpp",
        "motion_model/stationary_motion_model.hpp",
        "optimization/core/bounds.hpp",
        "optimization/core/composite.hpp",
        "optimization/core/constraint_set.hpp",
        "optimization/core/cost_term.hpp",
        "optimization/core/problem.hpp",
        "optimization/core/solver.hpp",
        "optimization/core/variable_set.hpp",
        "param_handler.hpp",
        "ply.hpp",
        "port.hpp",
        "signal_filters/filter_factory.hpp",
        "signal_filters/low_pass_filter.hpp",
        "signal_filters/signal_filter.hpp",
        "signal_processing/butterworth.hpp",
        "signal_processing/lowpass_filter.hpp",
        "signal_processing/lowpass_filter_1d.hpp",
        "state_estimation/kalman_filter/kalman_filter.hpp",
        "state_estimation/measurement/linear_measurement.hpp",
        "state_estimation/measurement/measurement_interface.hpp",
        "state_estimation/noise_model/noise_interface.hpp",
        "state_estimation/noise_model/uniform_noise.hpp",
        "state_estimation/noise_model/wiener_noise.hpp",
        "state_estimation/state_estimation_interface.hpp",
        "state_vector/common_states.hpp",
        "state_vector/common_variables.hpp",
        "state_vector/generic_state.hpp",
        "state_vector/variable.hpp",
        "string_util.hpp",
        "task.hpp",
        "thread_pool.hpp",
        "time.hpp",
        "time_util.hpp",
        "transform/rigid_transform.hpp",
        "transform/transform.hpp",
        "version.hpp",
        ":generate_config",
    ],
    copts = ['-DMODULE_NAME=\"common\"'],
    include_prefix = "autonomy/common",
    deps = [
        "//:automsgs",
        "//:autonomy_headers",
        "@eigen//:eigen",
        "@com_github_google_glog//:glog",
        "@com_google_protobuf//:protobuf",
        "//:pthread",
    ],
)

filegroup(
    name = "runtime_data",
    srcs = glob(
        [
            "conf/**",
            "dag/**",
            "launch/**",
        ],
        allow_empty = True,
    ),
)
