load(
    "//tools:package.bzl",
    "autonomy_module_copts",
    "autonomy_cc_binary",
    "autonomy_cc_library",
)

package(default_visibility = ["//visibility:public"])

autonomy_cc_library(
    name = "autonomy_task",
    srcs = [
        "behavior_tree/bt_defaults.cpp",
        "behavior_tree/bt_node_registry.cpp",
        "behavior_tree/bt_profile.cpp",
        "behavior_tree/bt_runner.cpp",
        "behavior_tree/bt_status_logger.cpp",
        "behavior_tree/plugins/action/sleep_action.cpp",
        "behavior_tree/plugins/control/pipeline_sequence.cpp",
        "behavior_tree/plugins/control/recovery_node.cpp",
        "behavior_tree/plugins/control/round_robin_node.cpp",
        "behavior_tree/plugins/decorator/rate_controller.cpp",
        "charging/charging.cpp",
        "charging/charging_client.cpp",
        "charging/plugins/action/dock_approach_action.cpp",
        "charging/plugins/action/dock_connect_action.cpp",
        "charging/plugins/action/dock_search_action.cpp",
        "charging/plugins/condition/charger_visible_condition.cpp",
        "common/navigator.cpp",
        "common/task_action_client.cpp",
        "common/transform_listener.cpp",
        "exploration/exploration.cpp",
        "localization/localization.cpp",
        "localization/localization_client.cpp",
        "localization/plugins/action/start_localization_action.cpp",
        "localization/plugins/action/stop_localization_action.cpp",
        "localization/plugins/condition/localization_ready_condition.cpp",
        "manipulation/manipulation.cpp",
        "mapping/mapping.cpp",
        "mapping/mapping_client.cpp",
        "mapping/plugins/action/load_map_action.cpp",
        "mapping/plugins/action/set_initial_pose_action.cpp",
        "navigation/navigation.cpp",
        "navigation/navigation_client.cpp",
        "navigation/options.cpp",
        "navigation/plugins/action/back_up_action.cpp",
        "navigation/plugins/action/cancel_motion_action.cpp",
        "navigation/plugins/action/clear_costmap_action.cpp",
        "navigation/plugins/action/compute_path_through_poses_action.cpp",
        "navigation/plugins/action/compute_path_to_pose_action.cpp",
        "navigation/plugins/action/drive_on_heading_action.cpp",
        "navigation/plugins/action/follow_path_action.cpp",
        "navigation/plugins/action/plugin_selector_action.cpp",
        "navigation/plugins/action/remove_in_collision_goals_action.cpp",
        "navigation/plugins/action/remove_passed_goals_action.cpp",
        "navigation/plugins/action/smooth_path_action.cpp",
        "navigation/plugins/action/spin_action.cpp",
        "navigation/plugins/action/wait_action.cpp",
        "navigation/plugins/condition/goal_reached_condition.cpp",
        "navigation/plugins/condition/initial_pose_received_condition.cpp",
        "navigation/plugins/condition/path_valid_condition.cpp",
        "navigation/plugins/condition/planning_ready_condition.cpp",
        "navigation/plugins/condition/servers_ready_condition.cpp",
        "navigation/plugins/condition/time_expired_condition.cpp",
        "scheduler/scheduler.cpp",
        "task_server.cpp",
        "teleop/assist_options.cpp",
        "teleop/client.cpp",
        "teleop/cloud_feeder.cpp",
        "teleop/mppi_assist.cpp",
        "teleop/path_selector.cpp",
        "teleop/path_viz.cpp",
        "teleop/plugins/action/apply_velocity.cpp",
        "teleop/plugins/condition/perception_ok.cpp",
        "teleop/plugins/condition/watchdog_ok.cpp",
        "teleop/teleop.cpp",
        "tracking/plugins/action/compute_follow_goal_action.cpp",
        "tracking/plugins/action/follow_shadow_path_action.cpp",
        "tracking/plugins/condition/target_locked_condition.cpp",
        "tracking/tracking.cpp",
        "tracking/tracking_client.cpp",
        "voice/voice.cpp",
    ],
    hdrs = [
        "behavior_tree/blackboard_client.hpp",
        "behavior_tree/bt_defaults.hpp",
        "behavior_tree/bt_node_registry.hpp",
        "behavior_tree/bt_profile.hpp",
        "behavior_tree/bt_runner.hpp",
        "behavior_tree/bt_status_logger.hpp",
        "behavior_tree/bt_task_app.hpp",
        "behavior_tree/plugin_utils.hpp",
        "behavior_tree/plugins/bt_node_base.hpp",
        "charging/charging.hpp",
        "charging/charging_client.hpp",
        "charging/plugins/plugin_utils.hpp",
        "common/goal_ingress.hpp",
        "common/names.hpp",
        "common/navigator.hpp",
        "common/task_action_client.hpp",
        "common/task_action_client_impl.hpp",
        "common/task_interface.hpp",
        "common/transform_listener.hpp",
        "common/typed_task.hpp",
        "exploration/exploration.hpp",
        "localization/localization.hpp",
        "localization/localization_client.hpp",
        "localization/plugins/plugin_utils.hpp",
        "manipulation/manipulation.hpp",
        "mapping/mapping.hpp",
        "mapping/mapping_client.hpp",
        "mapping/plugins/plugin_utils.hpp",
        "navigation/action_session.hpp",
        "navigation/behavior_tree_navigator.hpp",
        "navigation/constants.hpp",
        "navigation/interface.hpp",
        "navigation/navigation.hpp",
        "navigation/navigation_client.hpp",
        "navigation/options.hpp",
        "navigation/plugins/async_remote_action_node.hpp",
        "navigation/plugins/plugin_utils.hpp",
        "register_tasks.hpp",
        "scheduler/scheduler.hpp",
        "task_server.hpp",
        "teleop/assist_options.hpp",
        "teleop/client.hpp",
        "teleop/cloud_feeder.hpp",
        "teleop/constants.hpp",
        "teleop/mppi_assist.hpp",
        "teleop/obstacle_grid.hpp",
        "teleop/path_selector.hpp",
        "teleop/path_viz.hpp",
        "teleop/plugins/plugin_utils.hpp",
        "teleop/teleop.hpp",
        "tracking/plugins/plugin_utils.hpp",
        "tracking/tracking.hpp",
        "tracking/tracking_client.hpp",
        "voice/voice.hpp",
    ],
    copts = autonomy_module_copts("task"),
    include_prefix = "autonomy/task",
    deps = [
        "//autonomy/common:autonomy_common",
        "//autonomy/transform:autonomy_transform",
        "//autonomy/map:autonomy_map",
        "//autonomy/control:autonomy_control",
        "//:autolink",
        "//:automsgs",
        "//:autonomy_headers",
        "@eigen//:eigen",
        "@com_github_google_glog//:glog",
        "@com_google_protobuf//:protobuf",
        "//:pthread",
    ],
)

autonomy_cc_binary(
    name = "autonomy.task",
    srcs = ["task_main.cpp"],
    deps = [
        ":autonomy_task",
        "@com_github_google_glog//:glog",
        "@com_github_gflags_gflags//:gflags",
    ],
)

filegroup(
    name = "runtime_data",
    srcs = glob(
        [
            "conf/**",
            "dag/**",
            "launch/**",
        ],
        allow_empty = True,
    ),
)

filegroup(
    name = "protos",
    srcs = glob(["**/*.proto"]),
    visibility = ["//visibility:public"],
)
