<?xml version="1.0"?>
<package format="3">
  <name>base</name>
  <version>0.1.0</version>
  <description>Workspace library with no dependencies.</description>
  <maintainer email="dev@example.com">autocmake</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>autocmake</buildtool_depend>

  <export>
    <build_type>autocmake</build_type>
  </export>
</package>
