#!/usr/bin/env python3
# Copyright 2026 The Openbot Authors (duyongquan)
#
# Scans autonomy/task C++ plugin sources for BT_REGISTER_NODES /
# registerNodeType / providedPorts and regenerates tree_nodes_model.xml.
#
# Usage (from repo root):
#   python3 src/autonomy/config/task/behavior_tree/export_tree_nodes_model.py
#   python3 src/autonomy/config/task/behavior_tree/export_tree_nodes_model.py --stdout
#
# Optional:
#   --task-root PATH   override autonomy/task source root
#   --output PATH      override output XML path

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional


@dataclass
class Port:
    direction: str
    name: str
    type_name: str = "string"
    default_value: str = ""
    description: str = ""


@dataclass
class NodeModel:
    kind: str
    node_id: str
    ports: List[Port] = field(default_factory=list)


REGISTER_RE = re.compile(
    r'registerNodeType\s*<[^>]+>\s*\(\s*"([^"]+)"\s*\)', re.MULTILINE
)
INPUT_PORT_RE = re.compile(
    r'BT::InputPort\s*<([^>]+)>\s*\(\s*"([^"]+)"(?:\s*,\s*([^,\)]+))?(?:\s*,\s*"([^"]*)")?\s*\)'
)
OUTPUT_PORT_RE = re.compile(
    r'BT::OutputPort\s*<([^>]+)>\s*\(\s*"([^"]+)"(?:\s*,\s*"([^"]*)")?\s*\)'
)
PROVIDED_PORTS_RE = re.compile(
    r'static\s+BT::PortsList\s+providedPorts\s*\(\s*\)\s*\{([^}]*)\}',
    re.MULTILINE | re.DOTALL,
)


CPP_TYPE_MAP = {
    "std::string": "string",
    "int": "int",
    "float": "float",
    "double": "double",
    "bool": "bool",
    "automsgs::msgs::nav_msgs::Path": "Path",
    "automsgs::msgs::geometry_msgs::PoseStamped": "PoseStamped",
    "std::vector<automsgs::msgs::geometry_msgs::PoseStamped>": "PoseStamped[]",
}


def normalize_type(cpp_type: str) -> str:
    cpp_type = cpp_type.strip()
    return CPP_TYPE_MAP.get(cpp_type, cpp_type.split("::")[-1])


def normalize_default(value: str) -> str:
    value = value.strip()
    if value.startswith('"') and value.endswith('"'):
        return value[1:-1]
    if value.endswith("f") and value[:-1].replace(".", "", 1).isdigit():
        return value[:-1]
    return value


def infer_kind(path: Path) -> str:
    parts = {part.lower() for part in path.parts}
    if "condition" in parts:
        return "Condition"
    if "decorator" in parts:
        return "Decorator"
    if "control" in parts:
        return "Control"
    return "Action"


def parse_ports(block: str) -> List[Port]:
    ports: List[Port] = []
    for match in INPUT_PORT_RE.finditer(block):
        cpp_type, name, default_value, description = match.groups()
        ports.append(
            Port(
                direction="input_port",
                name=name,
                type_name=normalize_type(cpp_type),
                default_value=normalize_default(default_value or ""),
                description=(description or "").strip(),
            )
        )
    for match in OUTPUT_PORT_RE.finditer(block):
        cpp_type, name, description = match.groups()
        ports.append(
            Port(
                direction="output_port",
                name=name,
                type_name=normalize_type(cpp_type),
                description=(description or "").strip(),
            )
        )
    return ports


def scan_task_root(task_root: Path) -> Dict[str, NodeModel]:
    models: Dict[str, NodeModel] = {}
    for cpp_path in sorted(task_root.rglob("*.cpp")):
        text = cpp_path.read_text(encoding="utf-8", errors="ignore")
        if "registerNodeType" not in text:
            continue

        ports_block = ""
        ports_match = PROVIDED_PORTS_RE.search(text)
        if ports_match:
            ports_block = ports_match.group(1)

        ports = parse_ports(ports_block)
        kind = infer_kind(cpp_path)

        for reg_match in REGISTER_RE.finditer(text):
            node_id = reg_match.group(1)
            models[node_id] = NodeModel(kind=kind, node_id=node_id, ports=list(ports))
    return models


def render_xml(models: Dict[str, NodeModel]) -> str:
    kind_order = {"Action": 0, "Condition": 1, "Control": 2, "Decorator": 3}
    sorted_models = sorted(
        models.values(),
        key=lambda model: (kind_order.get(model.kind, 99), model.node_id),
    )

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by export_tree_nodes_model.py; do not edit by hand unless needed. -->",
        '<root BTCPP_format="4">',
        "  <TreeNodesModel>",
    ]

    current_kind: Optional[str] = None
    for model in sorted_models:
        if model.kind != current_kind:
            if current_kind is not None:
                lines.append("")
            lines.append(f"    <!-- {model.kind}s -->")
            current_kind = model.kind

        if model.ports:
            lines.append(f'    <{model.kind} ID="{model.node_id}">')
            for port in model.ports:
                attrs = [f'name="{port.name}"', f'type="{port.type_name}"']
                if port.default_value:
                    attrs.append(f'default="{port.default_value}"')
                attr_text = " ".join(attrs)
                if port.description:
                    lines.append(
                        f"      <{port.direction} {attr_text}>{port.description}</{port.direction}>"
                    )
                else:
                    lines.append(f"      <{port.direction} {attr_text}/>")
            lines.append(f"    </{model.kind}>")
        else:
            lines.append(f'    <{model.kind} ID="{model.node_id}"/>')

    lines.extend(["  </TreeNodesModel>", "</root>", ""])
    return "\n".join(lines)


def default_paths() -> tuple[Path, Path]:
    script_path = Path(__file__).resolve()
    config_bt_root = script_path.parent
    repo_root = config_bt_root
    for _ in range(6):
        candidate = repo_root / "src" / "autonomy" / "autonomy" / "task"
        if candidate.is_dir():
            return candidate, config_bt_root / "tree_nodes_model.xml"
        if repo_root.parent == repo_root:
            break
        repo_root = repo_root.parent
    raise SystemExit("Unable to locate autonomy/task source tree")


def main() -> int:
    task_root_default, output_default = default_paths()

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--task-root", type=Path, default=task_root_default)
    parser.add_argument("--output", type=Path, default=output_default)
    parser.add_argument("--stdout", action="store_true", help="print XML to stdout")
    args = parser.parse_args()

    if not args.task_root.is_dir():
        print(f"task root not found: {args.task_root}", file=sys.stderr)
        return 1

    models = scan_task_root(args.task_root)
    xml = render_xml(models)

    if args.stdout:
        sys.stdout.write(xml)
        return 0

    args.output.write_text(xml, encoding="utf-8")
    print(f"Wrote {len(models)} node models to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
