// GENERATED BY tools/generate_automsgs_foxglove_registry.py — DO NOT EDIT.

#pragma once

#include <array>
#include <cstddef>
#include <string_view>

#include "autonomy/autoviz/core/convert/registry/automsgs_foxglove_registry.hpp"

namespace autoviz {
namespace converter {
namespace foxglove_registry_data {

namespace str {
inline constexpr char s0[] = "automsgs.msgs.builtin_interfaces.Duration";
inline constexpr char s1[] = "foxglove.Log";
inline constexpr char s2[] = "Log：protobuf TextFormat（通用）";
inline constexpr char s3[] = "automsgs.msgs.builtin_interfaces.Time";
inline constexpr char s4[] = "automsgs.msgs.diagnostic_msgs.DiagnosticArray";
inline constexpr char s5[] = "automsgs.msgs.diagnostic_msgs.DiagnosticStatus";
inline constexpr char s6[] = "automsgs.msgs.diagnostic_msgs.KeyValue";
inline constexpr char s7[] = "automsgs.msgs.geometry_msgs.Accel";
inline constexpr char s8[] = "automsgs.msgs.geometry_msgs.AccelStamped";
inline constexpr char s9[] = "automsgs.msgs.geometry_msgs.AccelWithCovariance";
inline constexpr char s10[] = "automsgs.msgs.geometry_msgs.AccelWithCovarianceStamped";
inline constexpr char s11[] = "automsgs.msgs.geometry_msgs.Inertia";
inline constexpr char s12[] = "automsgs.msgs.geometry_msgs.InertiaStamped";
inline constexpr char s13[] = "automsgs.msgs.geometry_msgs.Point";
inline constexpr char s14[] = "automsgs.msgs.geometry_msgs.Point32";
inline constexpr char s15[] = "automsgs.msgs.geometry_msgs.PointStamped";
inline constexpr char s16[] = "automsgs.msgs.geometry_msgs.Polygon";
inline constexpr char s17[] = "automsgs.msgs.geometry_msgs.PolygonStamped";
inline constexpr char s18[] = "automsgs.msgs.geometry_msgs.Pose";
inline constexpr char s19[] = "automsgs.msgs.geometry_msgs.Pose2D";
inline constexpr char s20[] = "automsgs.msgs.geometry_msgs.PoseArray";
inline constexpr char s21[] = "foxglove.PosesInFrame";
inline constexpr char s22[] = "3D：PosesInFrame";
inline constexpr char s23[] = "automsgs.msgs.geometry_msgs.PoseStamped";
inline constexpr char s24[] = "foxglove.PoseInFrame";
inline constexpr char s25[] = "3D：PoseInFrame";
inline constexpr char s26[] = "automsgs.msgs.geometry_msgs.PoseWithCovariance";
inline constexpr char s27[] = "automsgs.msgs.geometry_msgs.PoseWithCovarianceStamped";
inline constexpr char s28[] = "automsgs.msgs.geometry_msgs.Quaternion";
inline constexpr char s29[] = "automsgs.msgs.geometry_msgs.QuaternionStamped";
inline constexpr char s30[] = "automsgs.msgs.geometry_msgs.Transform";
inline constexpr char s31[] = "automsgs.msgs.geometry_msgs.TransformStamped";
inline constexpr char s32[] = "foxglove.FrameTransform";
inline constexpr char s33[] = "3D：FrameTransform（TF）";
inline constexpr char s34[] = "automsgs.msgs.geometry_msgs.Twist";
inline constexpr char s35[] = "automsgs.msgs.geometry_msgs.TwistStamped";
inline constexpr char s36[] = "automsgs.msgs.geometry_msgs.TwistWithCovariance";
inline constexpr char s37[] = "automsgs.msgs.geometry_msgs.TwistWithCovarianceStamped";
inline constexpr char s38[] = "automsgs.msgs.geometry_msgs.Vector3";
inline constexpr char s39[] = "automsgs.msgs.geometry_msgs.Vector3Stamped";
inline constexpr char s40[] = "automsgs.msgs.geometry_msgs.VelocityStamped";
inline constexpr char s41[] = "automsgs.msgs.geometry_msgs.Wrench";
inline constexpr char s42[] = "automsgs.msgs.geometry_msgs.WrenchStamped";
inline constexpr char s43[] = "automsgs.msgs.nav_msgs.GridCells";
inline constexpr char s44[] = "foxglove.SceneUpdate";
inline constexpr char s45[] = "3D：GridCells → 立方体单元";
inline constexpr char s46[] = "automsgs.msgs.nav_msgs.MapMetaData";
inline constexpr char s47[] = "automsgs.msgs.nav_msgs.OccupancyGrid";
inline constexpr char s48[] = "foxglove.Grid";
inline constexpr char s49[] = "Grid/地图；未实现时用 Log 回退";
inline constexpr char s50[] = "automsgs.msgs.nav_msgs.Odometry";
inline constexpr char s51[] = "3D：位姿为 PoseInFrame（header.frame_id）";
inline constexpr char s52[] = "automsgs.msgs.nav_msgs.Path";
inline constexpr char s53[] = "3D：SceneUpdate + LinePrimitive";
inline constexpr char s54[] = "automsgs.msgs.sensor_msgs.BatteryState";
inline constexpr char s55[] = "automsgs.msgs.sensor_msgs.CameraInfo";
inline constexpr char s56[] = "automsgs.msgs.sensor_msgs.ChannelFloat32";
inline constexpr char s57[] = "automsgs.msgs.sensor_msgs.CompressedImage";
inline constexpr char s58[] = "foxglove.CompressedImage";
inline constexpr char s59[] = "Image 面板；未实现时用 Log 回退";
inline constexpr char s60[] = "automsgs.msgs.sensor_msgs.FluidPressure";
inline constexpr char s61[] = "automsgs.msgs.sensor_msgs.Illuminance";
inline constexpr char s62[] = "automsgs.msgs.sensor_msgs.Image";
inline constexpr char s63[] = "foxglove.RawImage";
inline constexpr char s64[] = "RawImage；未实现时用 Log 回退";
inline constexpr char s65[] = "automsgs.msgs.sensor_msgs.Imu";
inline constexpr char s66[] = "automsgs.msgs.sensor_msgs.JointState";
inline constexpr char s67[] = "foxglove.JointState";
inline constexpr char s68[] = "目标 JointState；字段对齐后改专用转换，暂 TextFormat/Log";
inline constexpr char s69[] = "automsgs.msgs.sensor_msgs.Joy";
inline constexpr char s70[] = "automsgs.msgs.sensor_msgs.JoyFeedback";
inline constexpr char s71[] = "automsgs.msgs.sensor_msgs.JoyFeedbackArray";
inline constexpr char s72[] = "automsgs.msgs.sensor_msgs.LaserEcho";
inline constexpr char s73[] = "automsgs.msgs.sensor_msgs.LaserScan";
inline constexpr char s74[] = "foxglove.LaserScan";
inline constexpr char s75[] = "LaserScan 面板；未实现字段映射时用 Log 回退";
inline constexpr char s76[] = "automsgs.msgs.sensor_msgs.MagneticField";
inline constexpr char s77[] = "automsgs.msgs.sensor_msgs.MultiDOFJointState";
inline constexpr char s78[] = "automsgs.msgs.sensor_msgs.MultiEchoLaserScan";
inline constexpr char s79[] = "foxglove.PointCloud";
inline constexpr char s80[] = "3D：多回波展开为 PointCloud";
inline constexpr char s81[] = "automsgs.msgs.sensor_msgs.NavSatFix";
inline constexpr char s82[] = "foxglove.LocationFix";
inline constexpr char s83[] = "地图 LocationFix；未实现时用 Log 回退";
inline constexpr char s84[] = "automsgs.msgs.sensor_msgs.NavSatStatus";
inline constexpr char s85[] = "automsgs.msgs.sensor_msgs.PointCloud";
inline constexpr char s86[] = "旧版 PointCloud；未实现时用 Log 回退";
inline constexpr char s87[] = "automsgs.msgs.sensor_msgs.PointCloud2";
inline constexpr char s88[] = "PointCloud；未实现时用 Log 回退";
inline constexpr char s89[] = "automsgs.msgs.sensor_msgs.PointField";
inline constexpr char s90[] = "automsgs.msgs.sensor_msgs.Range";
inline constexpr char s91[] = "automsgs.msgs.sensor_msgs.RegionOfInterest";
inline constexpr char s92[] = "automsgs.msgs.sensor_msgs.RelativeHumidity";
inline constexpr char s93[] = "automsgs.msgs.sensor_msgs.Temperature";
inline constexpr char s94[] = "automsgs.msgs.sensor_msgs.TimeReference";
inline constexpr char s95[] = "automsgs.msgs.shape_msgs.Mesh";
inline constexpr char s96[] = "automsgs.msgs.shape_msgs.MeshTriangle";
inline constexpr char s97[] = "automsgs.msgs.shape_msgs.Plane";
inline constexpr char s98[] = "automsgs.msgs.shape_msgs.SolidPrimitive";
inline constexpr char s99[] = "automsgs.msgs.std_msgs.Int16MultiArray";
inline constexpr char s100[] = "automsgs.msgs.std_msgs.Int32";
inline constexpr char s101[] = "automsgs.msgs.std_msgs.Int32MultiArray";
inline constexpr char s102[] = "automsgs.msgs.std_msgs.Int64";
inline constexpr char s103[] = "automsgs.msgs.std_msgs.Int64MultiArray";
inline constexpr char s104[] = "automsgs.msgs.std_msgs.MultiArrayDimension";
inline constexpr char s105[] = "automsgs.msgs.std_msgs.MultiArrayLayout";
inline constexpr char s106[] = "automsgs.msgs.std_msgs.String";
inline constexpr char s107[] = "Log：正文为 String.data";
inline constexpr char s108[] = "automsgs.msgs.std_msgs.UInt16";
inline constexpr char s109[] = "automsgs.msgs.std_msgs.UInt16MultiArray";
inline constexpr char s110[] = "automsgs.msgs.std_msgs.UInt32";
inline constexpr char s111[] = "automsgs.msgs.std_msgs.UInt32MultiArray";
inline constexpr char s112[] = "automsgs.msgs.std_msgs.UInt64";
inline constexpr char s113[] = "automsgs.msgs.std_msgs.UInt64MultiArray";
inline constexpr char s114[] = "automsgs.msgs.std_msgs.UInt8";
inline constexpr char s115[] = "automsgs.msgs.std_msgs.UInt8MultiArray";
inline constexpr char s116[] = "automsgs.msgs.stereo_msgs.DisparityImage";
inline constexpr char s117[] = "automsgs.msgs.trajectory_msgs.JointTrajectory";
inline constexpr char s118[] = "automsgs.msgs.trajectory_msgs.JointTrajectoryPoint";
inline constexpr char s119[] = "automsgs.msgs.trajectory_msgs.MultiDOFJointTrajectory";
inline constexpr char s120[] = "automsgs.msgs.trajectory_msgs.MultiDOFJointTrajectoryPoint";
inline constexpr char s121[] = "automsgs.msgs.vision_msgs.BoundingBox2D";
inline constexpr char s122[] = "automsgs.msgs.vision_msgs.BoundingBox2DArray";
inline constexpr char s123[] = "automsgs.msgs.vision_msgs.BoundingBox3D";
inline constexpr char s124[] = "3D：单框 CubePrimitive";
inline constexpr char s125[] = "automsgs.msgs.vision_msgs.BoundingBox3DArray";
inline constexpr char s126[] = "3D：多框 SceneUpdate";
inline constexpr char s127[] = "automsgs.msgs.vision_msgs.Classification";
inline constexpr char s128[] = "automsgs.msgs.vision_msgs.Detection2D";
inline constexpr char s129[] = "automsgs.msgs.vision_msgs.Detection2DArray";
inline constexpr char s130[] = "automsgs.msgs.vision_msgs.Detection3D";
inline constexpr char s131[] = "3D：检测框 + 标签";
inline constexpr char s132[] = "automsgs.msgs.vision_msgs.Detection3DArray";
inline constexpr char s133[] = "3D：Detection3D 数组";
inline constexpr char s134[] = "automsgs.msgs.vision_msgs.LabelInfo";
inline constexpr char s135[] = "automsgs.msgs.vision_msgs.ObjectHypothesis";
inline constexpr char s136[] = "automsgs.msgs.vision_msgs.ObjectHypothesisWithPose";
inline constexpr char s137[] = "automsgs.msgs.vision_msgs.Point2D";
inline constexpr char s138[] = "automsgs.msgs.vision_msgs.Pose2D";
inline constexpr char s139[] = "automsgs.msgs.vision_msgs.VisionClass";
inline constexpr char s140[] = "automsgs.msgs.vision_msgs.VisionInfo";
inline constexpr char s141[] = "automsgs.msgs.visualization_msgs.ImageMarker";
inline constexpr char s142[] = "automsgs.msgs.visualization_msgs.InteractiveMarker";
inline constexpr char s143[] = "automsgs.msgs.visualization_msgs.InteractiveMarkerControl";
inline constexpr char s144[] = "automsgs.msgs.visualization_msgs.InteractiveMarkerFeedback";
inline constexpr char s145[] = "automsgs.msgs.visualization_msgs.InteractiveMarkerInit";
inline constexpr char s146[] = "automsgs.msgs.visualization_msgs.InteractiveMarkerPose";
inline constexpr char s147[] = "automsgs.msgs.visualization_msgs.InteractiveMarkerUpdate";
inline constexpr char s148[] = "automsgs.msgs.visualization_msgs.Marker";
inline constexpr char s149[] = "3D：SceneUpdate / Marker";
inline constexpr char s150[] = "automsgs.msgs.visualization_msgs.MarkerArray";
inline constexpr char s151[] = "3D：SceneUpdate / MarkerArray";
inline constexpr char s152[] = "automsgs.msgs.visualization_msgs.MenuEntry";
inline constexpr char s153[] = "automsgs.msgs.visualization_msgs.MeshFile";
inline constexpr char s154[] = "automsgs.msgs.visualization_msgs.UVCoordinate";
inline constexpr char s155[] = "automsgs.rpcs.charging.DockRequest";
inline constexpr char s156[] = "RPC 消息：Log / Raw";
inline constexpr char s157[] = "automsgs.rpcs.charging.DockResponse";
inline constexpr char s158[] = "automsgs.rpcs.charging.GetStatusRequest";
inline constexpr char s159[] = "automsgs.rpcs.charging.GetStatusResponse";
inline constexpr char s160[] = "automsgs.rpcs.charging.UndockRequest";
inline constexpr char s161[] = "automsgs.rpcs.charging.UndockResponse";
inline constexpr char s162[] = "automsgs.rpcs.common.Status";
inline constexpr char s163[] = "automsgs.rpcs.navigation.CancelRequest";
inline constexpr char s164[] = "automsgs.rpcs.navigation.CancelResponse";
inline constexpr char s165[] = "automsgs.rpcs.navigation.GetStatusRequest";
inline constexpr char s166[] = "automsgs.rpcs.navigation.GetStatusResponse";
inline constexpr char s167[] = "automsgs.rpcs.navigation.GoToRequest";
inline constexpr char s168[] = "automsgs.rpcs.navigation.GoToResponse";
inline constexpr char s169[] = "automsgs.rpcs.sensor.GetGridRequest";
inline constexpr char s170[] = "automsgs.rpcs.sensor.GetGridResponse";
inline constexpr char s171[] = "automsgs.rpcs.sensor.GetImageRequest";
inline constexpr char s172[] = "automsgs.rpcs.sensor.GetImageResponse";
inline constexpr char s173[] = "automsgs.rpcs.sensor.GetLaserScanRequest";
inline constexpr char s174[] = "automsgs.rpcs.sensor.GetLaserScanResponse";
inline constexpr char s175[] = "automsgs.rpcs.sensor.GetPointCloudRequest";
inline constexpr char s176[] = "automsgs.rpcs.sensor.GetPointCloudResponse";
inline constexpr char s177[] = "automsgs.rpcs.sensor.ListSensorsRequest";
inline constexpr char s178[] = "automsgs.rpcs.sensor.ListSensorsResponse";
inline constexpr char s179[] = "automsgs.rpcs.sensor.SensorInfo";
inline constexpr char s180[] = "automsgs.rpcs.task.CancelRequest";
inline constexpr char s181[] = "automsgs.rpcs.task.CancelResponse";
inline constexpr char s182[] = "automsgs.rpcs.task.GetStatusRequest";
inline constexpr char s183[] = "automsgs.rpcs.task.GetStatusResponse";
inline constexpr char s184[] = "automsgs.rpcs.task.RunRequest";
inline constexpr char s185[] = "automsgs.rpcs.task.RunResponse";
inline constexpr char s186[] = "automsgs.rpcs.vehicle.GetBatteryRequest";
inline constexpr char s187[] = "automsgs.rpcs.vehicle.GetBatteryResponse";
inline constexpr char s188[] = "automsgs.rpcs.vehicle.GetPoseRequest";
inline constexpr char s189[] = "automsgs.rpcs.vehicle.GetPoseResponse";
inline constexpr char s190[] = "automsgs.rpcs.vehicle.GetStatusRequest";
inline constexpr char s191[] = "automsgs.rpcs.vehicle.GetStatusResponse";
inline constexpr char s192[] = "automsgs.rpcs.world.DeleteMapRequest";
inline constexpr char s193[] = "automsgs.rpcs.world.DeleteMapResponse";
inline constexpr char s194[] = "automsgs.rpcs.world.GetLocPoseRequest";
inline constexpr char s195[] = "automsgs.rpcs.world.GetLocPoseResponse";
inline constexpr char s196[] = "automsgs.rpcs.world.GetLocStatusRequest";
inline constexpr char s197[] = "automsgs.rpcs.world.GetLocStatusResponse";
inline constexpr char s198[] = "automsgs.rpcs.world.GetMapMetadataRequest";
inline constexpr char s199[] = "automsgs.rpcs.world.GetMapMetadataResponse";
inline constexpr char s200[] = "automsgs.rpcs.world.GetMapRequest";
inline constexpr char s201[] = "automsgs.rpcs.world.GetMapResponse";
inline constexpr char s202[] = "automsgs.rpcs.world.ListMapsRequest";
inline constexpr char s203[] = "automsgs.rpcs.world.ListMapsResponse";
inline constexpr char s204[] = "automsgs.rpcs.world.MapSummary";
inline constexpr char s205[] = "automsgs.rpcs.world.SaveMapRequest";
inline constexpr char s206[] = "automsgs.rpcs.world.SaveMapResponse";
inline constexpr char s207[] = "automsgs.rpcs.world.SetCurrentMapRequest";
inline constexpr char s208[] = "automsgs.rpcs.world.SetCurrentMapResponse";
inline constexpr char s209[] = "automsgs.rpcs.world.SetInitialPoseRequest";
inline constexpr char s210[] = "automsgs.rpcs.world.SetInitialPoseResponse";
inline constexpr char s211[] = "automsgs.srvs.AddDiagnostics";
inline constexpr char s212[] = "服务封装消息：Log / Raw";
inline constexpr char s213[] = "automsgs.srvs.GetMap";
inline constexpr char s214[] = "automsgs.srvs.GetPlan";
inline constexpr char s215[] = "automsgs.srvs.LoadMap";
inline constexpr char s216[] = "automsgs.srvs.SelfTest";
inline constexpr char s217[] = "automsgs.srvs.SetBool";
inline constexpr char s218[] = "automsgs.srvs.SetMap";
inline constexpr char s219[] = "automsgs.srvs.Trigger";
}  // namespace str

struct Row {
  std::string_view proto_full_name;
  std::string_view foxglove_canonical_name;
  AutomsgsFoxgloveStrategy strategy;
  std::string_view studio_hint;
};

inline constexpr std::array<Row, 183> kRows{{
    Row{str::s0, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s3, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s4, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s5, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s6, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s7, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s8, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s9, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s10, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s11, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s12, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s13, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s14, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s15, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s16, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s17, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s18, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s19, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s20, str::s21, AutomsgsFoxgloveStrategy::kConvertToPosesInFrame, str::s22},
    Row{str::s23, str::s24, AutomsgsFoxgloveStrategy::kConvertToPoseInFrame, str::s25},
    Row{str::s26, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s27, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s28, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s29, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s30, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s31, str::s32, AutomsgsFoxgloveStrategy::kConvertToFrameTransform, str::s33},
    Row{str::s34, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s35, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s36, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s37, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s38, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s39, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s40, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s41, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s42, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s43, str::s44, AutomsgsFoxgloveStrategy::kConvertToSceneUpdate, str::s45},
    Row{str::s46, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s47, str::s48, AutomsgsFoxgloveStrategy::kConvertToGrid, str::s49},
    Row{str::s50, str::s24, AutomsgsFoxgloveStrategy::kConvertToPoseInFrame, str::s51},
    Row{str::s52, str::s44, AutomsgsFoxgloveStrategy::kConvertToSceneUpdate, str::s53},
    Row{str::s54, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s55, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s56, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s57, str::s58, AutomsgsFoxgloveStrategy::kConvertToImage, str::s59},
    Row{str::s60, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s61, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s62, str::s63, AutomsgsFoxgloveStrategy::kConvertToImage, str::s64},
    Row{str::s65, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s66, str::s67, AutomsgsFoxgloveStrategy::kConvertToLog, str::s68},
    Row{str::s69, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s70, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s71, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s72, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s73, str::s74, AutomsgsFoxgloveStrategy::kConvertToLaserScan, str::s75},
    Row{str::s76, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s77, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s78, str::s79, AutomsgsFoxgloveStrategy::kConvertToPointCloud, str::s80},
    Row{str::s81, str::s82, AutomsgsFoxgloveStrategy::kConvertToLocationFix, str::s83},
    Row{str::s84, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s85, str::s79, AutomsgsFoxgloveStrategy::kConvertToPointCloud, str::s86},
    Row{str::s87, str::s79, AutomsgsFoxgloveStrategy::kConvertToPointCloud, str::s88},
    Row{str::s89, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s90, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s91, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s92, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s93, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s94, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s95, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s96, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s97, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s98, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s99, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s100, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s101, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s102, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s103, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s104, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s105, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s106, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s107},
    Row{str::s108, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s109, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s110, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s111, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s112, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s113, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s114, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s115, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s116, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s117, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s118, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s119, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s120, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s121, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s122, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s123, str::s44, AutomsgsFoxgloveStrategy::kConvertToSceneUpdate, str::s124},
    Row{str::s125, str::s44, AutomsgsFoxgloveStrategy::kConvertToSceneUpdate, str::s126},
    Row{str::s127, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s128, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s129, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s130, str::s44, AutomsgsFoxgloveStrategy::kConvertToSceneUpdate, str::s131},
    Row{str::s132, str::s44, AutomsgsFoxgloveStrategy::kConvertToSceneUpdate, str::s133},
    Row{str::s134, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s135, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s136, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s137, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s138, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s139, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s140, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s141, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s142, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s143, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s144, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s145, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s146, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s147, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s148, str::s44, AutomsgsFoxgloveStrategy::kConvertToSceneUpdate, str::s149},
    Row{str::s150, str::s44, AutomsgsFoxgloveStrategy::kConvertToSceneUpdate, str::s151},
    Row{str::s152, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s153, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s154, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s2},
    Row{str::s155, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s157, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s158, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s159, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s160, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s161, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s162, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s163, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s164, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s165, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s166, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s167, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s168, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s169, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s170, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s171, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s172, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s173, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s174, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s175, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s176, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s177, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s178, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s179, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s180, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s181, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s182, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s183, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s184, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s185, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s186, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s187, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s188, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s189, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s190, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s191, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s192, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s193, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s194, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s195, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s196, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s197, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s198, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s199, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s200, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s201, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s202, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s203, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s204, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s205, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s206, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s207, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s208, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s209, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s210, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s156},
    Row{str::s211, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s212},
    Row{str::s213, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s212},
    Row{str::s214, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s212},
    Row{str::s215, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s212},
    Row{str::s216, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s212},
    Row{str::s217, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s212},
    Row{str::s218, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s212},
    Row{str::s219, str::s1, AutomsgsFoxgloveStrategy::kConvertToLog, str::s212},
}};

template <std::size_t N>
constexpr bool RowsAreSorted(const std::array<Row, N>& a) {
  for (std::size_t i = 1; i < N; ++i) {
    if (a[i - 1].proto_full_name >= a[i].proto_full_name) {
      return false;
    }
  }
  return true;
}

static_assert(RowsAreSorted(kRows),
              "foxglove registry rows must stay sorted by proto_full_name");

}  // namespace foxglove_registry_data
}  // namespace converter
}  // namespace autoviz
