load(
    "//tools:package.bzl",
    "autonomy_cc_binary",
    "autonomy_cc_library",
)

package(default_visibility = ["//visibility:public"])

autonomy_cc_library(
    name = "autonomy_control",
    srcs = [
        "checker/pose_progress_checker.cpp",
        "checker/position_goal_checker.cpp",
        "checker/simple_goal_checker.cpp",
        "checker/simple_progress_checker.cpp",
        "checker/stopped_goal_checker.cpp",
        "common/controller_interface.cpp",
        "control_options.cpp",
        "controller/graceful_controller/controller.cpp",
        "controller/graceful_controller/parameter_options.cpp",
        "controller/graceful_controller/path_handler.cpp",
        "controller/graceful_controller/smooth_control_law.cpp",
        "controller/graceful_controller/utils.cpp",
        "controller/mppi_controller/controller.cpp",
        "controller/mppi_controller/critic_manager.cpp",
        "controller/mppi_controller/critics/constraint_critic.cpp",
        "controller/mppi_controller/critics/cost_critic.cpp",
        "controller/mppi_controller/critics/goal_angle_critic.cpp",
        "controller/mppi_controller/critics/goal_critic.cpp",
        "controller/mppi_controller/critics/grid_obstacles_critic.cpp",
        "controller/mppi_controller/critics/obstacles_critic.cpp",
        "controller/mppi_controller/critics/path_align_critic.cpp",
        "controller/mppi_controller/critics/path_angle_critic.cpp",
        "controller/mppi_controller/critics/path_follow_critic.cpp",
        "controller/mppi_controller/critics/prefer_forward_critic.cpp",
        "controller/mppi_controller/critics/twirling_critic.cpp",
        "controller/mppi_controller/critics/velocity_deadband_critic.cpp",
        "controller/mppi_controller/optimizer.cpp",
        "controller/mppi_controller/tools/grid_map_buffer.cpp",
        "controller/mppi_controller/tools/mppi_options.cpp",
        "controller/mppi_controller/tools/noise_generator.cpp",
        "controller/mppi_controller/tools/path_handler.cpp",
        "controller/mppi_controller/tools/trajectory_visualizer.cpp",
        "controller/nmpc_controller/controller.cpp",
        "controller/nmpc_controller/differential_drive_cgmres_problem.cpp",
        "controller/nmpc_controller/differential_drive_problem.cpp",
        "controller/nmpc_controller/optimizer.cpp",
        "controller/nmpc_controller/parameter_defaults.cpp",
        "controller/nmpc_controller/parameter_options.cpp",
        "controller/nmpc_controller/path_reference.cpp",
        "controller/nmpc_controller/path_transformer.cpp",
        "controller/nmpc_controller/solver/cgmres/cgmres_solver.cpp",
        "controller/nmpc_controller/trajectory_collision_checker.cpp",
        "controller/pure_pursuit_controller/collision_checker.cpp",
        "controller/pure_pursuit_controller/controller.cpp",
        "controller/pure_pursuit_controller/parameter_handler.cpp",
        "controller/pure_pursuit_controller/parameter_options.cpp",
        "controller/pure_pursuit_controller/path_handler.cpp",
        "controller/sando_controller/cubic_control_point.cpp",
        "controller/sando_controller/geometric_path.cpp",
        "controller/sando_controller/hover_monitor.cpp",
        "controller/sando_controller/layered_trajectory_optimizer.cpp",
        "controller/sando_controller/miqp/daqp/src/api.c",
        "controller/sando_controller/miqp/daqp/src/auxiliary.c",
        "controller/sando_controller/miqp/daqp/src/avi.c",
        "controller/sando_controller/miqp/daqp/src/bnb.c",
        "controller/sando_controller/miqp/daqp/src/daqp.c",
        "controller/sando_controller/miqp/daqp/src/daqp_prox.c",
        "controller/sando_controller/miqp/daqp/src/eq_elim.c",
        "controller/sando_controller/miqp/daqp/src/factorization.c",
        "controller/sando_controller/miqp/daqp/src/hierarchical.c",
        "controller/sando_controller/miqp/daqp/src/utils.c",
        "controller/sando_controller/miqp/solver.cpp",
        "controller/sando_controller/obstacle_tracker.cpp",
        "controller/sando_controller/occupancy_grid.cpp",
        "controller/sando_controller/path_searcher.cpp",
        "controller/sando_controller/position_safety.cpp",
        "controller/sando_controller/safe_corridor.cpp",
        "controller/sando_controller/sando_controller.cpp",
        "controller/sando_controller/sando_defaults.cpp",
        "controller/sando_controller/sando_planner.cpp",
        "controller/sando_controller/trajectory_optimizer.cpp",
        "controller_autolink_actions.cpp",
        "controller_server.cpp",
        "tools/controllers/diff_drive/odometry.cpp",
        "tools/controllers/joint_trajectory/trajectory.cpp",
        "tools/controllers/mecanum_drive/odometry.cpp",
        "tools/controllers/omni_wheel_drive/odometry.cpp",
        "tools/controllers/steering/steering_kinematics.cpp",
        "tools/controllers/tricycle/odometry.cpp",
        "tools/controllers/tricycle/steering_limiter.cpp",
        "tools/controllers/tricycle/traction_limiter.cpp",
        "tools/dither.cpp",
        "tools/limited_proxy.cpp",
        "tools/pid.cpp",
        "tools/sine_sweep.cpp",
        "tools/sinusoid.cpp",
        "utils/controller_utils.cpp",
        "utils/conversions.cpp",
        "utils/odometry_utils.cpp",
        "utils/velocity_smoother.cpp",
    ],
    hdrs = [
        "checker/pose_progress_checker.hpp",
        "checker/position_goal_checker.hpp",
        "checker/simple_goal_checker.hpp",
        "checker/simple_progress_checker.hpp",
        "checker/stopped_goal_checker.hpp",
        "common/controller_exceptions.hpp",
        "common/controller_interface.hpp",
        "common/goal_checker_interface.hpp",
        "common/progress_checker_interface.hpp",
        "constants.hpp",
        "control_options.hpp",
        "controller/graceful_controller/controller.hpp",
        "controller/graceful_controller/ego_polar_coords.hpp",
        "controller/graceful_controller/parameter_options.hpp",
        "controller/graceful_controller/path_handler.hpp",
        "controller/graceful_controller/smooth_control_law.hpp",
        "controller/graceful_controller/utils.hpp",
        "controller/mppi_controller/controller.hpp",
        "controller/mppi_controller/critic_data.hpp",
        "controller/mppi_controller/critic_function.hpp",
        "controller/mppi_controller/critic_manager.hpp",
        "controller/mppi_controller/critics/constraint_critic.hpp",
        "controller/mppi_controller/critics/cost_critic.hpp",
        "controller/mppi_controller/critics/goal_angle_critic.hpp",
        "controller/mppi_controller/critics/goal_critic.hpp",
        "controller/mppi_controller/critics/grid_obstacles_critic.hpp",
        "controller/mppi_controller/critics/obstacles_critic.hpp",
        "controller/mppi_controller/critics/path_align_critic.hpp",
        "controller/mppi_controller/critics/path_angle_critic.hpp",
        "controller/mppi_controller/critics/path_follow_critic.hpp",
        "controller/mppi_controller/critics/prefer_forward_critic.hpp",
        "controller/mppi_controller/critics/twirling_critic.hpp",
        "controller/mppi_controller/critics/velocity_deadband_critic.hpp",
        "controller/mppi_controller/models/constraints.hpp",
        "controller/mppi_controller/models/control_sequence.hpp",
        "controller/mppi_controller/models/optimizer_settings.hpp",
        "controller/mppi_controller/models/path.hpp",
        "controller/mppi_controller/models/state.hpp",
        "controller/mppi_controller/models/trajectories.hpp",
        "controller/mppi_controller/motion_models.hpp",
        "controller/mppi_controller/optimizer.hpp",
        "controller/mppi_controller/tools/grid_map_buffer.hpp",
        "controller/mppi_controller/tools/mppi_options.hpp",
        "controller/mppi_controller/tools/noise_generator.hpp",
        "controller/mppi_controller/tools/path_handler.hpp",
        "controller/mppi_controller/tools/trajectory_visualizer.hpp",
        "controller/mppi_controller/tools/utils.hpp",
        "controller/nmpc_controller/controller.hpp",
        "controller/nmpc_controller/differential_drive_cgmres_problem.hpp",
        "controller/nmpc_controller/differential_drive_problem.hpp",
        "controller/nmpc_controller/optimizer.hpp",
        "controller/nmpc_controller/parameter_defaults.hpp",
        "controller/nmpc_controller/parameter_options.hpp",
        "controller/nmpc_controller/path_reference.hpp",
        "controller/nmpc_controller/path_transformer.hpp",
        "controller/nmpc_controller/solver/cgmres/cgmres_problem.hpp",
        "controller/nmpc_controller/solver/cgmres/cgmres_solver.hpp",
        "controller/nmpc_controller/solver/cgmres/euler_ode_solver.hpp",
        "controller/nmpc_controller/solver/cgmres/gmres.hpp",
        "controller/nmpc_controller/solver/cgmres/ode_solver.hpp",
        "controller/nmpc_controller/solver/cgmres/runge_kutta_ode_solver.hpp",
        "controller/nmpc_controller/solver/ddp/box_qp.hpp",
        "controller/nmpc_controller/solver/ddp/ddp_problem.hpp",
        "controller/nmpc_controller/solver/ddp/ddp_solver.hpp",
        "controller/nmpc_controller/solver/ddp/ddp_solver_impl.hpp",
        "controller/nmpc_controller/solver/fmpc/fmpc_problem.hpp",
        "controller/nmpc_controller/solver/fmpc/fmpc_solver.hpp",
        "controller/nmpc_controller/solver/fmpc/fmpc_solver_impl.hpp",
        "controller/nmpc_controller/solver/fmpc/math_utils.hpp",
        "controller/nmpc_controller/trajectory_collision_checker.hpp",
        "controller/pure_pursuit_controller/collision_checker.hpp",
        "controller/pure_pursuit_controller/controller.hpp",
        "controller/pure_pursuit_controller/parameter_handler.hpp",
        "controller/pure_pursuit_controller/parameter_options.hpp",
        "controller/pure_pursuit_controller/path_handler.hpp",
        "controller/pure_pursuit_controller/regulation_functions.hpp",
        "controller/sando_controller/cubic_control_point.hpp",
        "controller/sando_controller/geometric_path.hpp",
        "controller/sando_controller/hover_monitor.hpp",
        "controller/sando_controller/layered_trajectory_optimizer.hpp",
        "controller/sando_controller/miqp/daqp/include/api.h",
        "controller/sando_controller/miqp/daqp/include/auxiliary.h",
        "controller/sando_controller/miqp/daqp/include/avi.h",
        "controller/sando_controller/miqp/daqp/include/bnb.h",
        "controller/sando_controller/miqp/daqp/include/constants.h",
        "controller/sando_controller/miqp/daqp/include/daqp.h",
        "controller/sando_controller/miqp/daqp/include/daqp_prox.h",
        "controller/sando_controller/miqp/daqp/include/eq_elim.h",
        "controller/sando_controller/miqp/daqp/include/factorization.h",
        "controller/sando_controller/miqp/daqp/include/hierarchical.h",
        "controller/sando_controller/miqp/daqp/include/types.h",
        "controller/sando_controller/miqp/daqp/include/utils.h",
        "controller/sando_controller/miqp/solver.hpp",
        "controller/sando_controller/obstacle_tracker.hpp",
        "controller/sando_controller/occupancy_grid.hpp",
        "controller/sando_controller/path_searcher.hpp",
        "controller/sando_controller/position_safety.hpp",
        "controller/sando_controller/safe_corridor.hpp",
        "controller/sando_controller/sando_controller.hpp",
        "controller/sando_controller/sando_defaults.hpp",
        "controller/sando_controller/sando_planner.hpp",
        "controller/sando_controller/trajectory_optimizer.hpp",
        "controller/sando_controller/types.hpp",
        "controller_server.hpp",
        "tools/controllers/admittance/admittance_rule.hpp",
        "tools/controllers/diff_drive/kinematics.hpp",
        "tools/controllers/diff_drive/odometry.hpp",
        "tools/controllers/diff_drive/speed_limiter.hpp",
        "tools/controllers/gripper/gripper_command.hpp",
        "tools/controllers/joint_trajectory/interpolation_methods.hpp",
        "tools/controllers/joint_trajectory/tolerances.hpp",
        "tools/controllers/joint_trajectory/trajectory.hpp",
        "tools/controllers/joint_trajectory/trajectory_tracker.hpp",
        "tools/controllers/joint_trajectory/trajectory_types.hpp",
        "tools/controllers/mecanum_drive/odometry.hpp",
        "tools/controllers/omni_wheel_drive/odometry.hpp",
        "tools/controllers/steering/steering_kinematics.hpp",
        "tools/controllers/steering/twist_to_steering.hpp",
        "tools/controllers/tricycle/odometry.hpp",
        "tools/controllers/tricycle/steering_limiter.hpp",
        "tools/controllers/tricycle/traction_limiter.hpp",
        "tools/dither.hpp",
        "tools/exponential_filter.hpp",
        "tools/filter_chain.hpp",
        "tools/filters.hpp",
        "tools/gravity_compensation.hpp",
        "tools/limited_proxy.hpp",
        "tools/low_pass_filter.hpp",
        "tools/multi_dof_pid.hpp",
        "tools/pid.hpp",
        "tools/rate_limiter.hpp",
        "tools/realtime_box.hpp",
        "tools/rolling_mean.hpp",
        "tools/sine_sweep.hpp",
        "tools/sinusoid.hpp",
        "utils/controller_utils.hpp",
        "utils/conversions.hpp",
        "utils/odometry_utils.hpp",
        "utils/velocity_smoother.hpp",
    ],
    copts = ['-DMODULE_NAME=\"control\"'],
    include_prefix = "autonomy/control",
    deps = [
        "//autonomy/common:autonomy_common",
        "//autonomy/transform:autonomy_transform",
        "//autonomy/map:autonomy_map",
        "//:autolink",
        "//:automsgs",
        "//:autonomy_headers",
        "@eigen//:eigen",
        "@com_github_google_glog//:glog",
        "@com_google_protobuf//:protobuf",
        "//:pthread",
    ],
)

autonomy_cc_binary(
    name = "autonomy.control",
    srcs = ["control_main.cpp"],
    deps = [
        ":autonomy_control",
        "@com_github_google_glog//:glog",
        "@com_github_gflags_gflags//:gflags",
    ],
)

filegroup(
    name = "runtime_data",
    srcs = glob(
        [
            "conf/**",
            "dag/**",
            "launch/**",
        ],
        allow_empty = True,
    ),
)
