syntax = "proto3";

package automsgs.msgs.sensor_msgs;

import "automsgs/msgs/std_msgs/header.proto";
import "automsgs/msgs/sensor_msgs/region_of_interest.proto";

// Camera calibration and acquisition info.
message CameraInfo {
  // Time of image acquisition, camera coordinate frame ID.
  automsgs.msgs.std_msgs.Header header = 1;

  // Calibrated image dimensions.
  uint32 height = 2;
  uint32 width = 3;

  // Distortion model (e.g. "plumb_bob").
  string distortion_model = 4;

  // Distortion parameters.
  repeated double d = 5;  // length depends on model

  // Intrinsic camera matrix K (3x3, row-major, length 9).
  repeated double k = 6;

  // Rectification matrix R (3x3, row-major, length 9).
  repeated double r = 7;

  // Projection matrix P (3x4, row-major, length 12).
  repeated double p = 8;

  // Binning settings.
  uint32 binning_x = 9;
  uint32 binning_y = 10;

  // Region of interest.
  RegionOfInterest roi = 11;
}

