syntax = "proto3";

package automsgs.msgs.sensor_msgs;

import "automsgs/msgs/std_msgs/header.proto";
import "automsgs/msgs/geometry_msgs/quaternion.proto";
import "automsgs/msgs/geometry_msgs/vector3.proto";

// IMU data.
message Imu {
  automsgs.msgs.std_msgs.Header header = 1;

  automsgs.msgs.geometry_msgs.Quaternion orientation = 2;
  // Row-major 3x3 covariance (length 9).
  repeated double orientation_covariance = 3;

  automsgs.msgs.geometry_msgs.Vector3 angular_velocity = 4;
  repeated double angular_velocity_covariance = 5;

  automsgs.msgs.geometry_msgs.Vector3 linear_acceleration = 6;
  repeated double linear_acceleration_covariance = 7;
}

