syntax = "proto3";

package automsgs.msgs.sensor_msgs;

import "automsgs/msgs/std_msgs/header.proto";
import "automsgs/msgs/sensor_msgs/nav_sat_status.proto";

// Navigation Satellite fix for any Global Navigation Satellite System.
// Specified using the WGS 84 reference ellipsoid.
message NavSatFix {
  automsgs.msgs.std_msgs.Header header = 1;

  // Satellite fix status information.
  NavSatStatus status = 2;

  // Latitude [degrees]. Positive is north of equator; negative is south.
  double latitude = 3;

  // Longitude [degrees]. Positive is east of prime meridian; negative is west.
  double longitude = 4;

  // Altitude [m] above the WGS 84 ellipsoid (NaN if not available).
  double altitude = 5;

  // Position covariance [m^2] in ENU, row-major 3x3, length 9.
  repeated double position_covariance = 6;

  // Covariance type.
  enum CovarianceType {
    COVARIANCE_TYPE_UNKNOWN = 0;
    COVARIANCE_TYPE_APPROXIMATED = 1;
    COVARIANCE_TYPE_DIAGONAL_KNOWN = 2;
    COVARIANCE_TYPE_KNOWN = 3;
  }

  CovarianceType position_covariance_type = 7;
}

