
syntax = "proto3";

package automsgs.msgs.sensor_msgs;

import "automsgs/msgs/std_msgs/header.proto";

// Single range reading from an active ranger.
message Range {
  automsgs.msgs.std_msgs.Header header = 1;

  // Radiation type.
  enum RadiationType {
    ULTRASOUND = 0;
    INFRARED = 1;
  }

  RadiationType radiation_type = 2;

  // Size of the arc the distance reading is valid for [rad].
  float field_of_view = 3;

  // Minimum and maximum range values [m].
  float min_range = 4;
  float max_range = 5;

  // Range data [m].
  float range = 6;
}
