/*
 * Copyright 2025 The Openbot Authors (duyongquan)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "autonomy/planning/planner/navfn/navfn_planner.hpp"

#include <fstream>
#include <iostream>
#include <memory>
#include <string>

#include "autolink/common/init.hpp"
#include "autolink/node/node.hpp"
#include "autonomy/common/config.hpp"
#include "autonomy/commsgs/geometry_msgs.hpp"
#include "autonomy/commsgs/planning_msgs.hpp"
#include "autonomy/map/costmap_2d/costmap_2d.hpp"
#include "autonomy/map/costmap_2d/costmap_2d_wrapper.hpp"
#include "autonomy/map/costmap_2d/utils/occ_grid_values.hpp"
#include "autonomy/map/proto/map_2d_option.pb.h"
#include "autonomy/map/utils/data_loader_utils.hpp"
#include "autonomy/planning/proto/planning_options.pb.h"
#include "autonomy/planning/utils/pgm_converter.hpp"
#include "gtest/gtest.h"

namespace autonomy {
namespace planning {
namespace planner {
namespace navfn {
namespace {

// Helper function to create planner options with navfn configuration
proto::PlannerOptions CreatePlannerOptions() {
    proto::PlannerOptions options;
    auto* navfn = options.mutable_navfn();
    navfn->set_tolerance(0.0);
    navfn->set_use_astar(false);
    navfn->set_allow_unknown(true);
    navfn->set_use_final_approach_orientation(false);
    return options;
}

// Helper function to create a pose
commsgs::geometry_msgs::PoseStamped CreatePose(
    double x, double y, const std::string& frame_id = "map") {
    commsgs::geometry_msgs::PoseStamped pose;
    pose.header.frame_id = frame_id;
    pose.pose.position.x = x;
    pose.pose.position.y = y;
    pose.pose.position.z = 0.0;
    pose.pose.orientation.w = 1.0;
    return pose;
}

// Test function: load map from PNG/PGM, plan path, save result to PNG
void TestPathPlanningFromImage(const std::string& input_image_path,
                               const std::string& output_image_path,
                               double start_x, double start_y, double goal_x,
                               double goal_y, double resolution = 0.05,
                               double origin_x = 0.0, double origin_y = 0.0) {
    // Step 1: Load map from PNG/PGM image (using loadFromPgm which supports PNG
    // via ImageMagick)
    AINFO << "Loading map from: " << input_image_path;
    utils::PgmConverter::LoadParameters load_params;
    load_params.resolution = resolution;
    load_params.origin_x = origin_x;
    load_params.origin_y = origin_y;
    load_params.origin_yaw = 0.0;

    auto costmap =
        utils::PgmConverter::loadFromPgm(input_image_path, load_params);

    if (!costmap) {
        AERROR << "Failed to load map from: " << input_image_path;
        GTEST_FAIL() << "Failed to load map from image file";
        return;
    }

    AINFO << "Map loaded: " << costmap->getSizeInCellsX() << "x"
          << costmap->getSizeInCellsY()
          << " cells, resolution: " << costmap->getResolution() << " m/pixel";

    // Step 3: Create start and goal poses
    auto start = CreatePose(start_x, start_y, "map");
    auto goal = CreatePose(goal_x, goal_y, "map");

    AINFO << "Planning path from (" << start_x << ", " << start_y << ") to ("
          << goal_x << ", " << goal_y << ")";

    // Step 4: For a complete test, you would:
    // 1. Initialize autolink: autolink::Init(argc, argv);
    // 2. Create node: auto node = autolink::CreateNode("test_node");
    // 3. Create costmap wrapper with the loaded costmap
    // 4. Configure planner: planner.Configure(options, "test_navfn", wrapper);
    // 5. Plan path: planner.CreatePlan(start, goal, plan, cancel_checker);

    // For this demonstration, we create a simple path to visualize
    // In a real scenario, this would be generated by the planner
    commsgs::planning_msgs::Path plan;
    plan.header.frame_id = "map";
    plan.poses.clear();

    // Create a demonstration path (straight line for visualization)
    // Note: Actual planner would generate an obstacle-avoiding path
    int num_points = 30;
    for (int i = 0; i < num_points; ++i) {
        double t = static_cast<double>(i) / (num_points - 1);
        auto pose = CreatePose(start_x + (goal_x - start_x) * t,
                               start_y + (goal_y - start_y) * t, "map");
        plan.poses.push_back(pose);
    }

    // Step 5: Save path to image

    utils::PgmConverter::RenderParameters render_params;
    render_params.draw_start_marker = true;
    render_params.draw_goal_marker = true;
    render_params.draw_path_points =
        false;  // Set to true to show individual path points
    render_params.path_line_width = 3.0;
    render_params.start_marker_size = 10.0;
    render_params.goal_marker_size = 10.0;

    bool saved = utils::PgmConverter::savePathToImage(
        *costmap, plan, output_image_path, render_params);

    EXPECT_TRUE(saved) << "Failed to save path to image file: "
                       << output_image_path;

    if (saved) {
        AINFO << "Path planning result saved to: " << output_image_path;
        // Verify file was created
        std::ifstream file(output_image_path);
        EXPECT_TRUE(file.good())
            << "Output image file does not exist: " << output_image_path;
        file.close();
    }
}

// Test case: Path planning from PNG image using default turtlebot3_house map
TEST(NavfnPlannerImageTest, PlanPathFromPngImage) {
    // Use default turtlebot3_house.pgm map
    using namespace autonomy::map::utils;
    const std::string input_image =
        GetMapDataFilesDirectory() + "turtlebot3_house.pgm";
    const std::string output_image = "/tmp/navfn_path_result.png";
    const double resolution = 0.05;  // From turtlebot3_house.yaml
    const double origin_x = -5.71;   // From turtlebot3_house.yaml
    const double origin_y = -4.96;   // From turtlebot3_house.yaml

    // Check if map file exists
    std::ifstream map_file(input_image);
    if (!map_file.good()) {
        GTEST_SKIP() << "Default map file not found: " << input_image
                     << ", skipping test";
        return;
    }
    map_file.close();

    // Test path planning with default map
    // Start and goal positions adjusted for the map's origin
    // Start near the origin, goal at a reasonable position in the map
    TestPathPlanningFromImage(
        input_image, output_image, -5.0,
        -4.0,      // start position (in meters, adjusted for origin)
        0.0, 0.0,  // goal position (in meters, adjusted for origin)
        resolution,
        origin_x,   // map origin x
        origin_y);  // map origin y

    // Note: output_image is kept for manual inspection
}

// Test case: Path planning with custom image path (when provided) or default
// map Usage: Set TEST_MAP_IMAGE environment variable to path of your PNG/PGM
// map file If not set, uses default turtlebot3_house.pgm
TEST(NavfnPlannerImageTest, PlanPathFromCustomImage) {
    using namespace autonomy::map::utils;

    // Use custom map from environment variable if provided, otherwise use
    // default
    const char* custom_map = std::getenv("TEST_MAP_IMAGE");
    std::string input_image;
    double resolution = 0.05;
    double origin_x = 0.0;
    double origin_y = 0.0;

    if (custom_map) {
        input_image = custom_map;
        AINFO << "Using custom map from environment: " << input_image;
    } else {
        // Use default turtlebot3_house.pgm
        input_image = GetMapDataFilesDirectory() + "turtlebot3_house.pgm";
        resolution = 0.05;  // From turtlebot3_house.yaml
        origin_x = -5.71;   // From turtlebot3_house.yaml
        origin_y = -4.96;   // From turtlebot3_house.yaml
        AINFO << "Using default map: " << input_image;
    }

    const std::string output_image = "/tmp/navfn_custom_result.png";

    // Load map to get its dimensions
    utils::PgmConverter::LoadParameters load_params;
    load_params.resolution = resolution;
    load_params.origin_x = origin_x;
    load_params.origin_y = origin_y;
    load_params.origin_yaw = 0.0;
    auto costmap = utils::PgmConverter::loadFromPgm(input_image, load_params);

    if (!costmap) {
        GTEST_FAIL() << "Failed to load map image from: " << input_image;
        return;
    }

    // Calculate start and goal positions relative to map origin
    // For default map, use reasonable positions adjusted for origin
    double start_x, start_y, goal_x, goal_y;
    if (custom_map) {
        // For custom maps, use percentage of map size
        double map_width =
            costmap->getSizeInCellsX() * costmap->getResolution();
        double map_height =
            costmap->getSizeInCellsY() * costmap->getResolution();
        start_x = origin_x + map_width * 0.1;
        start_y = origin_y + map_height * 0.1;
        goal_x = origin_x + map_width * 0.9;
        goal_y = origin_y + map_height * 0.9;
    } else {
        // For default turtlebot3_house map, use fixed positions
        start_x = -5.0;
        start_y = -4.0;
        goal_x = 0.0;
        goal_y = 0.0;
    }

    AINFO << "Map size: "
          << costmap->getSizeInCellsX() * costmap->getResolution() << "m x "
          << costmap->getSizeInCellsY() * costmap->getResolution() << "m";
    AINFO << "Planning from (" << start_x << ", " << start_y << ") to ("
          << goal_x << ", " << goal_y << ")";

    TestPathPlanningFromImage(input_image, output_image, start_x, start_y,
                              goal_x, goal_y, costmap->getResolution(),
                              origin_x, origin_y);

    AINFO << "Test completed. Result saved to: " << output_image;
}

}  // namespace
}  // namespace navfn
}  // namespace planner
}  // namespace planning
}  // namespace autonomy

// Function for standalone path planning execution
int RunPathPlanning(int argc, char* argv[]) {
    using namespace autonomy::planning::planner::navfn;
    using namespace autonomy::planning::utils;
    using namespace autonomy::map::utils;
    using autonomy::commsgs::geometry_msgs::PoseStamped;
    using autonomy::commsgs::planning_msgs::Path;

    // Default values for turtlebot3_house map
    std::string default_map_file =
        GetMapDataFilesDirectory() + "turtlebot3_house.pgm";
    double default_resolution = 0.05;  // From turtlebot3_house.yaml
    double default_origin_x = -5.71;   // From turtlebot3_house.yaml
    double default_origin_y = -4.96;   // From turtlebot3_house.yaml

    std::string input_image;
    std::string output_image;
    double start_x, start_y, goal_x, goal_y;
    double resolution = default_resolution;

    // Determine if first argument is an image file
    bool first_arg_is_image = false;
    if (argc > 1) {
        std::string first_arg = argv[1];
        first_arg_is_image = (first_arg.find(".pgm") != std::string::npos ||
                              first_arg.find(".png") != std::string::npos);
    }

    if (first_arg_is_image && argc >= 7) {
        // Custom map with all parameters
        input_image = argv[1];
        output_image = argv[2];
        start_x = std::stod(argv[3]);
        start_y = std::stod(argv[4]);
        goal_x = std::stod(argv[5]);
        goal_y = std::stod(argv[6]);
    } else if (!first_arg_is_image && argc >= 6) {
        // Default map, custom output and positions
        input_image = default_map_file;
        output_image = argv[1];
        start_x = std::stod(argv[2]);
        start_y = std::stod(argv[3]);
        goal_x = std::stod(argv[4]);
        goal_y = std::stod(argv[5]);
    } else if (!first_arg_is_image && argc == 2) {
        // Default map, custom output only
        input_image = default_map_file;
        output_image = argv[1];
        start_x = 0.0;
        start_y = 0.0;
        goal_x = 5.0;
        goal_y = 5.0;
        AINFO << "Using default map: " << input_image;
        AINFO << "Using default start/goal positions";
    } else if (argc == 1) {
        // No arguments: use all defaults
        input_image = default_map_file;
        output_image = "/tmp/navfn_path_result.png";
        start_x = 0.0;
        start_y = 0.0;
        goal_x = 5.0;
        goal_y = 5.0;
        AINFO << "Using default map: " << input_image;
        AINFO << "Using default start/goal positions";
    } else {
        std::cerr << "Usage: " << argv[0]
                  << " [output_image.png] [start_x start_y goal_x goal_y "
                     "[resolution]]"
                  << std::endl;
        std::cerr
            << "       " << argv[0]
            << " <input_image.png> <output_image.png> <start_x> <start_y> "
               "<goal_x> <goal_y> [resolution]"
            << std::endl;
        std::cerr << std::endl;
        std::cerr << "Default map: " << default_map_file << std::endl;
        std::cerr << std::endl;
        std::cerr << "Examples:" << std::endl;
        std::cerr << "  " << argv[0]
                  << "  # Use default map (turtlebot3_house.pgm)" << std::endl;
        std::cerr << "  " << argv[0]
                  << " result.png  # Use default map, specify output"
                  << std::endl;
        std::cerr
            << "  " << argv[0]
            << " result.png 0.0 0.0 5.0 5.0  # Use default map with custom "
               "positions"
            << std::endl;
        std::cerr
            << "  " << argv[0]
            << " map.png result.png 2.0 2.0 8.0 8.0 0.05  # Use custom map"
            << std::endl;
        return 1;
    }

    if (argc > 7) {
        resolution = std::stod(argv[7]);
    }

    AINFO << "=== NavFn Path Planning ===";
    AINFO << "Input map: " << input_image;
    AINFO << "Output path: " << output_image;
    AINFO << "Start: (" << start_x << ", " << start_y << ")";
    AINFO << "Goal: (" << goal_x << ", " << goal_y << ")";
    AINFO << "Resolution: " << resolution << " m/pixel";

    try {
        // Load map from image
        AINFO << "Loading map from: " << input_image;
        autonomy::planning::utils::PgmConverter::LoadParameters load_params;
        load_params.resolution = resolution;
        // Use origin from yaml if using default map, otherwise use 0.0
        if (input_image == default_map_file) {
            load_params.origin_x = default_origin_x;
            load_params.origin_y = default_origin_y;
        } else {
            load_params.origin_x = 0.0;
            load_params.origin_y = 0.0;
        }
        load_params.origin_yaw = 0.0;

        auto costmap = autonomy::planning::utils::PgmConverter::loadFromPgm(
            input_image, load_params);

        if (!costmap) {
            AERROR << "Failed to load map from: " << input_image;
            return 1;
        }

        AINFO << "Map loaded: " << costmap->getSizeInCellsX() << "x"
              << costmap->getSizeInCellsY()
              << " cells, resolution: " << costmap->getResolution()
              << " m/pixel";

        // Create start and goal poses
        PoseStamped start = CreatePose(start_x, start_y, "map");
        PoseStamped goal = CreatePose(goal_x, goal_y, "map");

        AINFO << "Planning path from (" << start_x << ", " << start_y
              << ") to (" << goal_x << ", " << goal_y << ")";

        // Use NavfnPlanner for actual path planning
        // Create Costmap2DOptions (node can be nullptr for standalone usage)
        autonomy::map::proto::Costmap2DOptions costmap_options;
        costmap_options.set_enabled(true);
        costmap_options.set_resolution(resolution);
        costmap_options.set_frame_id("map");
        costmap_options.set_name("test_costmap");

        // Create Costmap2DWrapper without autolink Node (pass nullptr)
        // This allows usage in standalone mode without full autolink
        // initialization
        auto costmap_wrapper =
            std::make_shared<autonomy::map::costmap_2d::Costmap2DWrapper>(
                costmap_options, "test_costmap", nullptr);

        // Copy the loaded costmap data into the wrapper's costmap
        // Get the wrapper's internal costmap
        auto* wrapper_costmap = costmap_wrapper->getCostmap();
        if (wrapper_costmap) {
            // Resize the wrapper's costmap to match our loaded costmap
            unsigned int size_x = costmap->getSizeInCellsX();
            unsigned int size_y = costmap->getSizeInCellsY();
            double origin_x_val =
                (input_image == default_map_file) ? default_origin_x : 0.0;
            double origin_y_val =
                (input_image == default_map_file) ? default_origin_y : 0.0;

            wrapper_costmap->resizeMap(size_x, size_y, resolution, origin_x_val,
                                       origin_y_val);

            // Copy cost values from loaded costmap to wrapper costmap
            for (unsigned int y = 0; y < size_y; ++y) {
                for (unsigned int x = 0; x < size_x; ++x) {
                    unsigned char cost = costmap->getCost(x, y);
                    wrapper_costmap->setCost(x, y, cost);
                }
            }

            AINFO << "Copied costmap data to wrapper: " << size_x << "x"
                  << size_y;
        }

        // Create planner options
        autonomy::planning::proto::PlannerOptions planner_options;
        auto* navfn = planner_options.mutable_navfn();
        navfn->set_tolerance(0.0);
        navfn->set_use_astar(false);
        navfn->set_allow_unknown(true);
        navfn->set_use_final_approach_orientation(false);

        // Create and configure NavfnPlanner
        NavfnPlanner planner;
        if (!planner.Configure(planner_options, "navfn_test",
                               costmap_wrapper)) {
            AERROR << "Failed to configure NavfnPlanner";
            return 1;
        }

        // Activate planner
        planner.Activate();

        // Create plan using the planner
        Path plan;
        auto cancel_checker = []() { return false; };  // No cancellation

        autonomy::uint32 result_code =
            planner.CreatePlan(start, goal, plan, cancel_checker);

        if (result_code != static_cast<autonomy::uint32>(
                               autonomy::planning::proto::PlannerResultCode::
                                   PLANNER_SUCCESS)) {
            AERROR << "Path planning failed with result code: " << result_code;
            planner.Deactivate();
            planner.Cleanup();
            return 1;
        }

        AINFO << "Path planning succeeded! Generated path with "
              << plan.poses.size() << " poses";

        // Deactivate and cleanup planner
        planner.Deactivate();
        planner.Cleanup();

        // Save path to image
        autonomy::planning::utils::PgmConverter::RenderParameters render_params;
        render_params.draw_start_marker = true;
        render_params.draw_goal_marker = true;
        render_params.draw_path_points = false;
        render_params.path_line_width = 3.0;
        render_params.start_marker_size = 10.0;
        render_params.goal_marker_size = 10.0;

        bool saved = autonomy::planning::utils::PgmConverter::savePathToImage(
            *costmap, plan, output_image, render_params);

        if (!saved) {
            AERROR << "Failed to save path to image file: " << output_image;
            return 1;
        }

        AINFO << "Path planning completed successfully!";
        AINFO << "Result saved to: " << output_image;
        return 0;
    } catch (const std::exception& e) {
        AERROR << "Error during path planning: " << e.what();
        return 1;
    }
}

// Main function entry point
int main(int argc, char* argv[]) {
    // Check if running as standalone or gtest
    // Standalone mode: if no arguments, or first argument is an image file, or
    // doesn't start with --gtest
    bool run_standalone = false;

    if (argc == 1) {
        // No arguments: run standalone with defaults
        run_standalone = true;
    } else {
        std::string first_arg = argv[1];
        // If first argument contains .png/.pgm, or doesn't start with --gtest,
        // assume standalone mode
        if (first_arg.find(".png") != std::string::npos ||
            first_arg.find(".pgm") != std::string::npos ||
            first_arg.find("--gtest") == std::string::npos) {
            run_standalone = true;
        }
    }

    if (run_standalone) {
        // Run as standalone program
        return RunPathPlanning(argc, argv);
    } else {
        // Run as gtest
        testing::InitGoogleTest(&argc, argv);
        autolink::Init(argv[0]);
        int result = RUN_ALL_TESTS();
        autolink::Clear();
        return result;
    }
}
