// Copyright 2025 The Openbot Authors （duyongquan）
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package automsgs.msgs.vehicle_msgs;

import "automsgs/msgs/builtin_interfaces/time.proto";
import "automsgs/msgs/status_msgs/status_msgs.proto";
import "automsgs/msgs/vehicle_msgs/event_severity.proto";
import "automsgs/msgs/vehicle_msgs/robot_event_type.proto";
import "automsgs/msgs/vehicle_msgs/robot_task_type.proto";

// 事件推送（ReceiveBotEvents）
message RobotEvent {
  automsgs.msgs.builtin_interfaces.Time timestamp = 1;
  RobotEventType type = 2;
  EventSeverity severity = 3;
  RobotTaskType task_type = 4;
  string cmd_id = 5;
  string message = 6;
  automsgs.msgs.status_msgs.StatusCode error_code = 7;
}
