// Copyright 2026 The Openbot Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package autonomy.task.proto;

import "automsgs/msgs/geometry_msgs/pose_stamped.proto";
import "automsgs/task/common.proto";

message TrackAction {
  message Goal {
    string id = 1;
    Cmd cmd = 2;
    float distance = 3;  // m follow distance
    oneof target {
      automsgs.msgs.geometry_msgs.PoseStamped pose = 4;
      string track_id = 5;
    }
  }
  message Feedback {
    Status status = 1;
    float distance = 2;
    automsgs.msgs.geometry_msgs.PoseStamped pose = 3;
  }
  message Result {
    Status status = 1;
    string error = 2;
  }
}
