# Install rules for standalone autodriver builds.

install(
  TARGETS autodriver
  EXPORT autodriverTargets
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

install(
  DIRECTORY ${AUTODRIVER_ROOT_DIR}/autodriver/
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/autodriver
  FILES_MATCHING PATTERN "*.hpp"
)

install(
  FILES ${AUTODRIVER_GENERATED_DIR}/conf/conf.hpp
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/autodriver/conf
)

install(
  DIRECTORY ${AUTODRIVER_ROOT_DIR}/config/
  DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/autodriver/config
  FILES_MATCHING PATTERN "*.yaml"
)

install(TARGETS autodriver_hub RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})

if(AUTODRIVER_BUILD_EXAMPLES)
  install(TARGETS autodriver_demo RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
endif()

install(
  DIRECTORY ${AUTODRIVER_ROOT_DIR}/launch/
  DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/autodriver/launch
  FILES_MATCHING PATTERN "*.launch"
)

install(
  EXPORT autodriverTargets
  FILE autodriverTargets.cmake
  NAMESPACE autodriver::
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/autodriver
)
