/*
 * Copyright 2026 The Openbot Authors
 */

/**
 * @file action_pack.hpp
 * @brief action_traits_t / action_pack + BRIDGE_BIND_ACTION_TRAITS.
 *
 * @details
 * Maps ActionVariable tags to CRTP policy leaves and packs them into
 * compile-time tuples for navigator (and future) action backends.
 * `BRIDGE_BIND_ACTION_TRAITS(Tag, TraitsT)` specializes `action_traits`
 * so `action_traits_t<variable::Tag>` resolves to `TraitsT`.
 *
 * @par Ownership
 * Pure compile-time types; no runtime ownership.
 *
 * @par Threading
 * N/A (header-only type maps).
 *
 * @see variable_tags.hpp
 * @see navigation_traits.hpp
 * @see ActionBackgroundInterface
 */

#pragma once

#include "autonomy/bridge/grpc/clients/variable_tags.hpp"
#include "autonomy/bridge/grpc/clients/navigation_traits.hpp"
#include "autonomy/bridge/grpc/clients/variable_tag.hpp"
#include "autonomy/common/helper_functions/type_traits.hpp"
#include "autonomy/common/macros.hpp"
#include <tuple>

namespace autonomy {
namespace bridge {
namespace grpc {
namespace clients {

/**
 * @brief Map an ActionVariable tag to its CRTP policy type.
 *
 * @tparam VariableT Action variable tag (must specialize action_traits).
 *
 * @details
 * Primary template is incomplete; specializations are generated by
 * BRIDGE_BIND_ACTION_TRAITS and expose a nested `type` alias.
 */
template <typename VariableT>
struct action_traits {
    /**
     * @brief Shared / weak / unique pointer aliases for action_traits.
     */
    AUTONOMY_SMART_PTR_DEFINITIONS(action_traits<VariableT>)
};

/**
 * @brief Bind variable::Tag → TraitsT for action_traits_t.
 *
 * @details
 * Expands to a full specialization of action_traits with SMART_PTR aliases
 * and `using type = TraitsT`.
 *
 * @param Tag     Unqualified name under `variable::` (e.g. NavigateToPose).
 * @param TraitsT CRTP policy type (e.g. navigator::NavigateToPoseTraits).
 */
#define BRIDGE_BIND_ACTION_TRAITS(Tag, TraitsT)                 \
    template <>                                                 \
    struct action_traits<variable::Tag> {                       \
        AUTONOMY_SMART_PTR_DEFINITIONS(action_traits<variable::Tag>) \
        /** @brief CRTP policy bound to variable::Tag. */       \
        using type = TraitsT;                                   \
    }

BRIDGE_BIND_ACTION_TRAITS(NavigateToPose, navigator::NavigateToPoseTraits);
BRIDGE_BIND_ACTION_TRAITS(NavigateThroughPoses,
                          navigator::NavigateThroughPosesTraits);

#undef BRIDGE_BIND_ACTION_TRAITS

/**
 * @brief Alias for the CRTP policy bound to VariableT.
 *
 * @tparam VariableT Action variable tag.
 */
template <typename VariableT>
using action_traits_t = typename action_traits<VariableT>::type;

/**
 * @brief Navigator action variable pack (ToPose + ThroughPoses).
 *
 * @details Tuple of ActionVariable tags used by navigator action backends.
 */
using NavigatorActions =
    std::tuple<variable::NavigateToPose, variable::NavigateThroughPoses>;

/**
 * @brief Compile-time pack of ActionVariable tags and their policies.
 *
 * @tparam VariableTs ActionVariable tags (static_assert enforced).
 *
 * @details
 * `Variables` is the tag tuple; `Policies` is the parallel tuple of
 * `action_traits_t<VariableTs>...` CRTP leaves.
 */
template <typename... VariableTs>
struct action_pack {
    /**
     * @brief Shared / weak / unique pointer aliases for action_pack.
     */
    AUTONOMY_SMART_PTR_DEFINITIONS(action_pack<VariableTs...>)

    static_assert(
        common::type_traits::conjunction<is_action_variable<VariableTs>...>::
            value,
        "\n\naction_pack requires ActionVariable tags.\n\n");

    /**
     * @brief Tuple of ActionVariable tags in pack order.
     */
    using Variables = std::tuple<VariableTs...>;

    /**
     * @brief Tuple of CRTP policies parallel to Variables.
     */
    using Policies = std::tuple<action_traits_t<VariableTs>...>;
};

/**
 * @brief Default navigator action_pack specialization alias.
 *
 * @details
 * `action_pack<variable::NavigateToPose, variable::NavigateThroughPoses>`.
 */
using NavigatorActionPack =
    action_pack<variable::NavigateToPose, variable::NavigateThroughPoses>;

}  // namespace clients
}  // namespace grpc
}  // namespace bridge
}  // namespace autonomy
