platform_name: kitti_stereo_00-02

frontend:
  mode: vo
  fusion: loose
  vo:
    enabled: true
  vio:
    enabled: false

camera:
  sensor: stereo
  fx: 718.856
  fy: 718.856
  cx: 607.1928
  cy: 185.2157
  baseline: 0.53716
  depth_threshold: 35.0

vocabulary: autonomy/localization/conf/atlas/orb_vocab.fbow

backend:
  type: ceres
  window_size: 10
  max_iterations: 15
