---
- name: Check for shared vault file
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/../inventory/group_vars/vault.yml"
  register: autonomy_vault_file

- name: Load shared vault variables
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../inventory/group_vars/vault.yml"
  when: autonomy_vault_file.stat.exists
  no_log: true
