# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unit_test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0funit_test.proto\x12\x0e\x61utolink.proto\"1\n\x08UnitTest\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x11\n\tcase_name\x18\x02 \x01(\t\"S\n\x07\x43hatter\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x17\n\x0flidar_timestamp\x18\x02 \x01(\x04\x12\x0b\n\x03seq\x18\x03 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\"?\n\x10\x43hatterBenchmark\x12\r\n\x05stamp\x18\x01 \x01(\x04\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\tb\x06proto3')



_UNITTEST = DESCRIPTOR.message_types_by_name['UnitTest']
_CHATTER = DESCRIPTOR.message_types_by_name['Chatter']
_CHATTERBENCHMARK = DESCRIPTOR.message_types_by_name['ChatterBenchmark']
UnitTest = _reflection.GeneratedProtocolMessageType('UnitTest', (_message.Message,), {
  'DESCRIPTOR' : _UNITTEST,
  '__module__' : 'unit_test_pb2'
  # @@protoc_insertion_point(class_scope:autolink.proto.UnitTest)
  })
_sym_db.RegisterMessage(UnitTest)

Chatter = _reflection.GeneratedProtocolMessageType('Chatter', (_message.Message,), {
  'DESCRIPTOR' : _CHATTER,
  '__module__' : 'unit_test_pb2'
  # @@protoc_insertion_point(class_scope:autolink.proto.Chatter)
  })
_sym_db.RegisterMessage(Chatter)

ChatterBenchmark = _reflection.GeneratedProtocolMessageType('ChatterBenchmark', (_message.Message,), {
  'DESCRIPTOR' : _CHATTERBENCHMARK,
  '__module__' : 'unit_test_pb2'
  # @@protoc_insertion_point(class_scope:autolink.proto.ChatterBenchmark)
  })
_sym_db.RegisterMessage(ChatterBenchmark)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNITTEST._serialized_start=35
  _UNITTEST._serialized_end=84
  _CHATTER._serialized_start=86
  _CHATTER._serialized_end=169
  _CHATTERBENCHMARK._serialized_start=171
  _CHATTERBENCHMARK._serialized_end=234
# @@protoc_insertion_point(module_scope)
