/*
 * Copyright 2016 The Cartographer Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <cmath>
#include <fstream>
#include <string>

#include <CLI/CLI.hpp>
#include <glog/logging.h>

#include "autonomy/common/cli_options.hpp"
#include "autonomy/localization/cartographer/common/port.hpp"
#include "autonomy/localization/cartographer/ground_truth/autogenerate_ground_truth.hpp"
#include "autonomy/localization/cartographer/ground_truth/proto/relations.pb.h"
#include "autonomy/localization/cartographer/io/proto_stream.h"
#include "autonomy/localization/cartographer/io/proto_stream_deserializer.h"
#include "autonomy/localization/cartographer/mapping/proto/pose_graph.pb.h"
#include "autonomy/localization/cartographer/transform/transform.hpp"

namespace cartographer {
namespace ground_truth {
namespace {

void Run(const std::string& pose_graph_filename, const std::string& output_filename, const double min_covered_distance,
         const double outlier_threshold_meters, const double outlier_threshold_radians) {
    LOG(INFO) << "Reading pose graph from '" << pose_graph_filename << "'...";
    mapping::proto::PoseGraph pose_graph = io::DeserializePoseGraphFromFile(pose_graph_filename);

    LOG(INFO) << "Autogenerating ground truth relations...";
    const proto::GroundTruth ground_truth =
        GenerateGroundTruth(pose_graph, min_covered_distance, outlier_threshold_meters, outlier_threshold_radians);
    LOG(INFO) << "Writing " << ground_truth.relation_size() << " relations to '" << output_filename << "'.";
    {
        std::ofstream output_stream(output_filename, std::ios_base::out | std::ios_base::binary);
        CHECK(ground_truth.SerializeToOstream(&output_stream)) << "Could not serialize ground truth data.";
        output_stream.close();
        CHECK(output_stream) << "Could not write ground truth data.";
    }
}

}  // namespace
}  // namespace ground_truth
}  // namespace cartographer

int main(int argc, char** argv) {
    std::string pose_graph_filename;
    std::string output_filename;
    double min_covered_distance = 100.;
    double outlier_threshold_meters = 0.15;
    double outlier_threshold_radians = 0.02;

    CLI::App app{
        "Semi-automatically generates ground truth data from a pose graph proto.\n"
        "\n"
        "The input should contain a single trajectory and should have been "
        "manually assessed to be correctly loop closed. Small local distortions "
        "are acceptable if they are tiny compared to the errors we want to "
        "assess using the generated ground truth data.\n"
        "\n"
        "All loop closure constraints separated by long covered distance are "
        "included in the output. Outliers are removed."};
    app.add_option("--pose_graph_filename", pose_graph_filename,
                   "Proto stream file containing the pose graph used to generate "
                   "ground truth data.")
        ->required();
    app.add_option("--output_filename", output_filename,
                   "File to write the ground truth proto to.")
        ->required();
    app.add_option("--min_covered_distance", min_covered_distance,
                   "Minimum covered distance in meters before a loop closure is "
                   "considered a candidate for autogenerated ground truth.")
        ->capture_default_str();
    app.add_option("--outlier_threshold_meters", outlier_threshold_meters,
                   "Distance in meters beyond which constraints are considered "
                   "outliers.")
        ->capture_default_str();
    app.add_option("--outlier_threshold_radians", outlier_threshold_radians,
                   "Distance in radians beyond which constraints are considered "
                   "outliers.")
        ->capture_default_str();

    autonomy::common::ParseOrExit(app, argc, argv);
    FLAGS_logtostderr = true;
    google::InitGoogleLogging(argv[0]);

    ::cartographer::ground_truth::Run(pose_graph_filename, output_filename, min_covered_distance,
                                      outlier_threshold_meters, outlier_threshold_radians);
    return EXIT_SUCCESS;
}
