/*
 * Copyright 2025 The Openbot Authors (duyongquan)
 */

/**
 * @file context.hpp
 * @brief Shared ExecutionContext for gRPC handlers: infra + DomainBundle.
 *
 * @details
 * Handlers obtain Context via async_grpc ExecutionContext casting. Domain
 * stubs are reached through domains() / navigator()… accessors; never
 * construct stubs inside handlers.
 *
 * Ownership: Context is the sole owner of muxer / idempotency / hub /
 * DomainBundle. WorkScheduler is a non-owning SharedPtr into the Server pool.
 * Domain accessors are generated by BRIDGE_CONTEXT_DOMAIN to avoid a second
 * hand-maintained facade over DomainBundle.
 *
 * @see DomainBundle
 * @see TaskMuxer
 * @see WorkScheduler
 */

#pragma once

#include <memory>

#include "autolink/node/node.hpp"
#include "autonomy/bridge/grpc/idempotency.hpp"
#include "autonomy/bridge/grpc/domains.hpp"
#include "autonomy/bridge/grpc/state_hub.hpp"
#include "autonomy/bridge/grpc/task_muxer.hpp"
#include "autonomy/bridge/grpc/work_scheduler.hpp"
#include "autonomy/bridge/proto/bridge_options.pb.h"
#include "autonomy/common/async_grpc/execution_context.h"
#include "autonomy/common/macros.hpp"

namespace autonomy {
namespace bridge {
namespace grpc {

/**
 * @brief Forward a DomainBundle accessor on Context (returns `T&`).
 *
 * @details
 * Expands to `auto& name() { return domains_.name(); }` so Handler macros
 * (`&Context::navigator`, `&Context::teleop`, …) keep working without a
 * hand-written duplicate of every domain getter.
 *
 * @param name DomainBundle accessor method name (e.g. `navigator`).
 */
#define BRIDGE_CONTEXT_DOMAIN(name) \
    auto& name() { return domains_.name(); }

/**
 * @brief Shared infra + DomainBundle for gRPC handlers.
 *
 * @details
 * Aggregates TaskMuxer, CommandIdempotencyCache, StateHub, WorkScheduler
 * (non-owning SharedPtr into the Server-owned pool), and DomainBundle by
 * value. Extends async_grpc::ExecutionContext so handler code can retrieve
 * this object from the RPC runtime.
 *
 * @par Invariants
 * - Owns muxer / hub / domains / idempotency; holds non-owning WorkScheduler
 *   SharedPtr that must outlive all stubs.
 * - Handlers use navigator()/… accessors only; never construct stubs here.
 * - Estop / CancelAll go through DomainBundle::CancelAll.
 * - Non-copyable; intended as a single shared ExecutionContext per Server.
 *
 * @par Threading
 * Accessors return references to components that have their own
 * synchronization where needed (muxer, hub, idempotency). CancelAllTasks /
 * EmergencyStop must not be called concurrently with DomainBundle teardown.
 *
 * @par Ownership
 * Server (or test harness) keeps Context alive for the process
 * lifetime of the async_grpc::Server. Muxer is SharedPtr (stubs retain
 * copies); idempotency / StateHub are UniquePtr (sole owner); DomainBundle
 * is a value member declared after infra so it tears down first.
 *
 * @see DomainBundle
 * @see handlers::StreamHandler
 */
class Context
    : public autonomy::common::async_grpc::ExecutionContext
{
public:
    /**
     * @brief Shared / weak / unique pointer aliases for Context.
     */
    AUTONOMY_SMART_PTR_DEFINITIONS(Context)

    /**
     * @brief Construct shared bridge execution context.
     *
     * @details
     * Builds TaskMuxer, CommandIdempotencyCache, StateHub, and DomainBundle.
     * The scheduler pointer is stored as SharedPtr and must remain valid for
     * the lifetime of every domain stub that schedules work.
     *
     * @param[in] node         Autolink node for stubs / StateHub readers.
     * @param[in] scheduler    Shared background worker pool (must outlive stubs).
     * @param[in] identity     Fleet / inventory fields for GetRobotFullInfo.
     * @param[in] capabilities Optional capability advertise overrides.
     */
    Context(
        std::shared_ptr<autolink::Node> node,
        WorkScheduler::SharedPtr scheduler,
        proto::RobotIdentityOptions identity = {},
        proto::CapabilitiesOptions capabilities = {});

    /**
     * @brief Destructor; DomainBundle tears down stubs / cancel hooks first.
     */
    ~Context() override = default;

    Context(const Context&) = delete;
    Context& operator=(const Context&) = delete;

    /**
     * @brief Return the shared exclusive-task muxer.
     *
     * @return Reference to TaskMuxer owned by this Context.
     *
     * @note Handlers and stubs share this instance; acquire/release is
     * synchronized inside TaskMuxer.
     */
    TaskMuxer& muxer() { return *muxer_; }

    /**
     * @brief Return the shared robot state / event hub.
     *
     * @return Reference to StateHub owned by this Context.
     */
    StateHub& state_hub() { return *state_hub_; }

    /**
     * @brief Return the shared background work scheduler.
     *
     * @return Reference to WorkScheduler (non-owning; owned by Server).
     *
     * @warning Do not destroy the Server-owned scheduler while Context /
     * stubs still Schedule work.
     */
    WorkScheduler& work_scheduler() { return *work_scheduler_; }

    /**
     * @brief Return the domain stub bundle.
     *
     * @return Reference to DomainBundle owned by this Context.
     */
    DomainBundle& domains() { return domains_; }

    /**
     * @brief Return configured robot identity options.
     *
     * @return Const reference to RobotIdentityOptions (fleet / inventory).
     */
    const proto::RobotIdentityOptions& identity() const { return identity_; }

    /**
     * @brief Return configured capability advertise options.
     *
     * @return Const reference to CapabilitiesOptions.
     */
    const proto::CapabilitiesOptions& capabilities() const {
        return capabilities_;
    }

    /**
     * @name Domain accessors (BRIDGE_CONTEXT_DOMAIN)
     * @brief Thin forwards to DomainBundle; used as `&Context::<name>` in macros.
     * @{
     */
    BRIDGE_CONTEXT_DOMAIN(navigator)
    BRIDGE_CONTEXT_DOMAIN(teleop)
    BRIDGE_CONTEXT_DOMAIN(follow)
    BRIDGE_CONTEXT_DOMAIN(charge)
    BRIDGE_CONTEXT_DOMAIN(mapping)
    BRIDGE_CONTEXT_DOMAIN(map_service)
    BRIDGE_CONTEXT_DOMAIN(localization)
    BRIDGE_CONTEXT_DOMAIN(exploration)
    BRIDGE_CONTEXT_DOMAIN(voice)
    BRIDGE_CONTEXT_DOMAIN(sensor)
    BRIDGE_CONTEXT_DOMAIN(system_monitor)
    /** @} */

    /**
     * @brief Cancel all active domain tasks via DomainBundle registry.
     *
     * @details
     * Invokes every registered CancelAction (navigator cancel, teleop reset,
     * …), then Clear()s the TaskMuxer slot. Does not shut down gRPC; safe to
     * call from Estop / CancelAll RPCs.
     *
     * @note EmergencyStop(true) latches muxer estop in addition to this.
     */
    void CancelAllTasks();

    /**
     * @brief Engage or clear emergency-stop and cancel tasks when engaging.
     *
     * @details
     * When @p engage is true: latch TaskMuxer estop (TryAcquire fails) and
     * call CancelAllTasks(). When false: clear the estop latch only.
     *
     * @param[in] engage true to latch estop and cancel; false to clear.
     *
     * @warning Engaging estop rejects all subsequent exclusive commands until
     * cleared; callers must clear explicitly after the hazard ends.
     */
    void EmergencyStop(bool engage);

private:
    /**
     * @brief Exclusive command slot shared by all domain stubs.
     *
     * @details SharedPtr so GoalChannel / Session stubs may retain copies
     * across scheduled Execute lambdas. Declared before domains_.
     */
    TaskMuxer::SharedPtr muxer_{nullptr};

    /**
     * @brief Short-lived cmd_id / goal_id dedupe cache (sole owner).
     *
     * @details Injected as raw pointer into Teleop / BackgroundCommandSession.
     */
    CommandIdempotencyCache::UniquePtr idempotency_{nullptr};

    /**
     * @brief Non-owning handle to the Server-owned worker pool.
     *
     * @details Must outlive every stub that calls Schedule / Enqueue.
     */
    WorkScheduler::SharedPtr work_scheduler_{nullptr};

    /**
     * @brief Cached `/robot_state` + muxer overlay for System RPCs (sole owner).
     */
    StateHub::UniquePtr state_hub_{nullptr};

    /**
     * @brief Domain stubs + CancelRegistry (value member).
     *
     * @details Declared after infra so destruction order tears domains down
     * first while muxer / idempotency / scheduler are still alive.
     */
    DomainBundle domains_;

    /**
     * @brief Fleet / inventory identity used by GetRobotFullInfo / GetInfo.
     */
    proto::RobotIdentityOptions identity_;

    /**
     * @brief Capability advertise overrides for Capabilities RPC.
     */
    proto::CapabilitiesOptions capabilities_;
};

#undef BRIDGE_CONTEXT_DOMAIN

}  // namespace grpc
}  // namespace bridge
}  // namespace autonomy
