// Copyright 2026 The Openbot Authors (duyongquan)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package automsgs.msgs.tf2_msgs;

message TF2Error {
  enum Error {
    NO_ERROR = 0;
    LOOKUP_ERROR = 1;
    CONNECTIVITY_ERROR = 2;
    EXTRAPOLATION_ERROR = 3;
    INVALID_ARGUMENT_ERROR = 4;
    TIMEOUT_ERROR = 5;
    TRANSFORM_ERROR = 6;
  }

  Error error = 1;
  string error_string = 2;
}
