// Copyright 2025 The Openbot Authors （duyongquan）
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package autonomy.map.proto;

import "autonomy/commsgs/proto/std_msgs.proto";
import "autonomy/commsgs/proto/builtin_interfaces.proto";
import "autonomy/commsgs/proto/geometry_msgs.proto";

message Costmap3DOptions
{
    // 是否启用3D代价地图
    bool enabled = 1;

    // map file path
    string map_file = 2;

    // costmap 3D name
    string name = 3;

    // frame id
    string frame_id = 4;

    // costmap 3D resolution
    double resolution = 5;

    // costmap 3D width
    int32 width = 6;

    // costmap 3D length
    int32 length = 7;

    // costmap 3D height
    int32 height = 8;

    // costmap 3D position x
    double position_x = 9;

    // costmap 3D position y
    double position_y = 10;

    // costmap 3D position z
    double position_z = 11;

    // costmap 3D position roll
    double position_roll = 12;

    // costmap 3D position pitch
    double position_pitch = 13;

    // costmap 3D position yaw
    double position_yaw = 14;
}
