// Copyright 2026 The Openbot Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package automsgs.msgs.moveit_msgs;

import "automsgs/msgs/moveit_msgs/planning_scene.proto";

message PlanningOptions {
  PlanningScene planning_scene_diff = 1;
  bool plan_only = 2;
  bool look_around = 3;
  int32 look_around_attempts = 4;
  double max_safe_execution_cost = 5;
  bool replan = 6;
  int32 replan_attempts = 7;
  double replan_delay = 8;
}
