// Copyright 2025 The Openbot Authors (duyongquan)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package autonomy.commsgs.proto.task_msgs;

import "autonomy/commsgs/proto/builtin_interfaces.proto";
import "autonomy/commsgs/proto/geometry_msgs.proto";
import "autonomy/commsgs/proto/planning_msgs.proto";
import "autonomy/commsgs/proto/std_msgs.proto";

// --- nav2_msgs/msg ---

message BehaviorTreeStatusChange {
  builtin_interfaces.Time timestamp = 1;
  string node_name = 2;
  uint32 uid = 3;
  string previous_status = 4;
  string current_status = 5;
}

message BehaviorTreeLog {
  builtin_interfaces.Time timestamp = 1;
  repeated BehaviorTreeStatusChange event_log = 2;
}

message SpeedLimit {
  std_msgs.Header header = 1;
  bool percentage = 2;
  float speed_limit = 3;
}

message CollisionMonitorState {
  uint32 action_type = 1;
  string polygon_name = 2;
}

message CollisionDetectorState {
  repeated string polygons = 1;
  repeated bool detections = 2;
}

message WaypointStatus {
  uint32 waypoint_status = 1;
  uint32 waypoint_index = 2;
  geometry_msgs.PoseStamped waypoint_pose = 3;
  uint32 error_code = 4;
  string error_msg = 5;
}

// --- nav2_msgs/srv ---

message IsPathValid {
  message Request {
    planning_msgs.Path path = 1;
    uint32 max_cost = 2;
    bool consider_unknown_as_obstacle = 3;
  }

  message Response {
    bool is_valid = 1;
    repeated int32 invalid_pose_indices = 2;
  }

  Request request = 1;
  Response response = 2;
}

message SetInitialPose {
  message Request {
    geometry_msgs.PoseWithCovarianceStamped pose = 1;
  }

  Request request = 1;
}

message ClearEntireCostmap {
  message Request {}

  message Response {}

  Request request = 1;
  Response response = 2;
}

message ManageLifecycleNodes {
  message Request {
    uint32 command = 1;
  }

  message Response {
    bool success = 1;
  }

  Request request = 1;
  Response response = 2;
}

// --- MBF-style error codes (BT blackboard error_code_id) ---

enum GetPathErrorCode {
  GET_PATH_SUCCESS = 0;
  GET_PATH_FAILURE = 50;
  GET_PATH_CANCELED = 51;
  GET_PATH_INVALID_START = 52;
  GET_PATH_INVALID_GOAL = 53;
  GET_PATH_BLOCKED_START = 54;
  GET_PATH_BLOCKED_GOAL = 55;
  GET_PATH_NO_PATH_FOUND = 56;
  GET_PATH_PAT_EXCEEDED = 57;
  GET_PATH_EMPTY_PATH = 58;
  GET_PATH_TF_ERROR = 59;
  GET_PATH_NOT_INITIALIZED = 60;
  GET_PATH_INVALID_PLUGIN = 61;
  GET_PATH_INTERNAL_ERROR = 62;
  GET_PATH_OUT_OF_MAP = 63;
  GET_PATH_MAP_ERROR = 64;
  GET_PATH_STOPPED = 65;
}

enum ExePathErrorCode {
  EXE_PATH_SUCCESS = 0;
  EXE_PATH_FAILURE = 100;
  EXE_PATH_CANCELED = 101;
  EXE_PATH_NO_VALID_CMD = 102;
  EXE_PATH_PAT_EXCEEDED = 103;
  EXE_PATH_COLLISION = 104;
  EXE_PATH_OSCILLATION = 105;
  EXE_PATH_ROBOT_STUCK = 106;
  EXE_PATH_MISSED_GOAL = 107;
  EXE_PATH_MISSED_PATH = 108;
  EXE_PATH_BLOCKED_GOAL = 109;
  EXE_PATH_BLOCKED_PATH = 110;
  EXE_PATH_INVALID_PATH = 111;
  EXE_PATH_TF_ERROR = 112;
  EXE_PATH_NOT_INITIALIZED = 113;
  EXE_PATH_INVALID_PLUGIN = 114;
  EXE_PATH_INTERNAL_ERROR = 115;
  EXE_PATH_OUT_OF_MAP = 116;
  EXE_PATH_MAP_ERROR = 117;
  EXE_PATH_STOPPED = 118;
}

enum RecoveryErrorCode {
  RECOVERY_SUCCESS = 0;
  RECOVERY_FAILURE = 150;
  RECOVERY_CANCELED = 151;
  RECOVERY_PAT_EXCEEDED = 152;
  RECOVERY_TF_ERROR = 153;
  RECOVERY_NOT_INITIALIZED = 154;
  RECOVERY_INVALID_PLUGIN = 155;
  RECOVERY_INTERNAL_ERROR = 156;
  RECOVERY_STOPPED = 157;
  RECOVERY_IMPASSABLE = 158;
}

enum MoveBaseErrorCode {
  MOVE_BASE_SUCCESS = 0;
  MOVE_BASE_FAILURE = 10;
  MOVE_BASE_CANCELED = 11;
  MOVE_BASE_COLLISION = 12;
  MOVE_BASE_OSCILLATION = 13;
  MOVE_BASE_START_BLOCKED = 14;
  MOVE_BASE_GOAL_BLOCKED = 15;
  MOVE_BASE_TF_ERROR = 16;
  MOVE_BASE_INTERNAL_ERROR = 17;
  MOVE_BASE_PLAN_FAILURE = 50;
  MOVE_BASE_CTRL_FAILURE = 100;
}

enum NavigateToPoseErrorCode {
  NAV_TO_POSE_NONE = 0;
  NAV_TO_POSE_UNKNOWN = 9000;
  NAV_TO_POSE_FAILED_TO_LOAD_BEHAVIOR_TREE = 9001;
  NAV_TO_POSE_TF_ERROR = 9002;
  NAV_TO_POSE_TIMEOUT = 9003;
  NAV_TO_POSE_NO_VALID_PATH = 9004;
  NAV_TO_POSE_CANCELED = 9005;
  NAV_TO_POSE_PREEMPTED = 9006;
  NAV_TO_POSE_INVALID_GOAL = 9007;
  NAV_TO_POSE_NOT_INITIALIZED = 9008;
  NAV_TO_POSE_PLANNER_FAILED = 9009;
  NAV_TO_POSE_CONTROLLER_FAILED = 9010;
  NAV_TO_POSE_SMOOTHER_FAILED = 9011;
  NAV_TO_POSE_PATH_INVALID = 9012;
  NAV_TO_POSE_GOAL_CHECKER_FAILED = 9013;
}

enum NavigateThroughPosesErrorCode {
  NAV_THROUGH_POSES_NONE = 0;
  NAV_THROUGH_POSES_UNKNOWN = 9100;
  NAV_THROUGH_POSES_FAILED_TO_LOAD_BEHAVIOR_TREE = 9101;
  NAV_THROUGH_POSES_TF_ERROR = 9102;
  NAV_THROUGH_POSES_TIMEOUT = 9103;
  NAV_THROUGH_POSES_NO_VALID_PATH = 9104;
  NAV_THROUGH_POSES_CANCELED = 9105;
  NAV_THROUGH_POSES_PREEMPTED = 9106;
  NAV_THROUGH_POSES_INVALID_GOAL = 9107;
  NAV_THROUGH_POSES_NOT_INITIALIZED = 9108;
  NAV_THROUGH_POSES_PLANNER_FAILED = 9109;
  NAV_THROUGH_POSES_CONTROLLER_FAILED = 9110;
  NAV_THROUGH_POSES_SMOOTHER_FAILED = 9111;
  NAV_THROUGH_POSES_PATH_INVALID = 9112;
  NAV_THROUGH_POSES_GOAL_CHECKER_FAILED = 9113;
}

enum FollowPathErrorCode {
  FOLLOW_PATH_NONE = 0;
  FOLLOW_PATH_UNKNOWN = 100;
  FOLLOW_PATH_INVALID_CONTROLLER = 101;
  FOLLOW_PATH_TF_ERROR = 102;
  FOLLOW_PATH_INVALID_PATH = 103;
  FOLLOW_PATH_PATIENCE_EXCEEDED = 104;
  FOLLOW_PATH_FAILED_TO_MAKE_PROGRESS = 105;
  FOLLOW_PATH_NO_VALID_CONTROL = 106;
  FOLLOW_PATH_CONTROLLER_TIMED_OUT = 107;
}

enum ComputePathToPoseErrorCode {
  COMPUTE_PATH_TO_POSE_NONE = 0;
  COMPUTE_PATH_TO_POSE_UNKNOWN = 200;
  COMPUTE_PATH_TO_POSE_INVALID_PLANNER = 201;
  COMPUTE_PATH_TO_POSE_TF_ERROR = 202;
  COMPUTE_PATH_TO_POSE_START_OUTSIDE_MAP = 203;
  COMPUTE_PATH_TO_POSE_GOAL_OUTSIDE_MAP = 204;
  COMPUTE_PATH_TO_POSE_START_OCCUPIED = 205;
  COMPUTE_PATH_TO_POSE_GOAL_OCCUPIED = 206;
  COMPUTE_PATH_TO_POSE_TIMEOUT = 207;
  COMPUTE_PATH_TO_POSE_NO_VALID_PATH = 208;
}

enum ComputePathThroughPosesErrorCode {
  COMPUTE_PATH_THROUGH_POSES_NONE = 0;
  COMPUTE_PATH_THROUGH_POSES_UNKNOWN = 300;
  COMPUTE_PATH_THROUGH_POSES_INVALID_PLANNER = 301;
  COMPUTE_PATH_THROUGH_POSES_TF_ERROR = 302;
  COMPUTE_PATH_THROUGH_POSES_START_OUTSIDE_MAP = 303;
  COMPUTE_PATH_THROUGH_POSES_GOAL_OUTSIDE_MAP = 304;
  COMPUTE_PATH_THROUGH_POSES_START_OCCUPIED = 305;
  COMPUTE_PATH_THROUGH_POSES_GOAL_OCCUPIED = 306;
  COMPUTE_PATH_THROUGH_POSES_TIMEOUT = 307;
  COMPUTE_PATH_THROUGH_POSES_NO_VALID_PATH = 308;
  COMPUTE_PATH_THROUGH_POSES_NO_WAYPOINTS = 309;
}

enum SmoothPathErrorCode {
  SMOOTH_PATH_NONE = 0;
  SMOOTH_PATH_UNKNOWN = 500;
  SMOOTH_PATH_INVALID_SMOOTHER = 501;
  SMOOTH_PATH_TIMEOUT = 502;
  SMOOTH_PATH_SMOOTHED_PATH_IN_COLLISION = 503;
  SMOOTH_PATH_FAILED_TO_SMOOTH = 504;
  SMOOTH_PATH_INVALID_PATH = 505;
}

enum FollowWaypointsErrorCode {
  FOLLOW_WAYPOINTS_NONE = 0;
  FOLLOW_WAYPOINTS_UNKNOWN = 600;
  FOLLOW_WAYPOINTS_TASK_EXECUTOR_FAILED = 601;
  FOLLOW_WAYPOINTS_NO_VALID_WAYPOINTS = 602;
  FOLLOW_WAYPOINTS_STOP_ON_MISSED_WAYPOINT = 603;
}

enum SpinErrorCode {
  SPIN_NONE = 0;
  SPIN_UNKNOWN = 700;
  SPIN_TIMEOUT = 701;
  SPIN_TF_ERROR = 702;
  SPIN_COLLISION_AHEAD = 703;
}

enum BackUpErrorCode {
  BACK_UP_NONE = 0;
  BACK_UP_UNKNOWN = 710;
  BACK_UP_TIMEOUT = 711;
  BACK_UP_TF_ERROR = 712;
  BACK_UP_INVALID_INPUT = 713;
  BACK_UP_COLLISION_AHEAD = 714;
}

enum DriveOnHeadingErrorCode {
  DRIVE_ON_HEADING_NONE = 0;
  DRIVE_ON_HEADING_UNKNOWN = 720;
  DRIVE_ON_HEADING_TIMEOUT = 721;
  DRIVE_ON_HEADING_TF_ERROR = 722;
  DRIVE_ON_HEADING_COLLISION_AHEAD = 723;
  DRIVE_ON_HEADING_INVALID_INPUT = 724;
}

enum WaitErrorCode {
  WAIT_NONE = 0;
  WAIT_UNKNOWN = 740;
  WAIT_TIMEOUT = 741;
}

enum AssistedTeleopErrorCode {
  ASSISTED_TELEOP_NONE = 0;
  ASSISTED_TELEOP_UNKNOWN = 730;
  ASSISTED_TELEOP_TIMEOUT = 731;
  ASSISTED_TELEOP_TF_ERROR = 732;
}

// --- nav2_msgs/action ---

message NavigateToPoseAction {
  message Goal {
    geometry_msgs.PoseStamped pose = 1;
    string behavior_tree = 2;
  }

  message Feedback {
    geometry_msgs.PoseStamped current_pose = 1;
    builtin_interfaces.Duration navigation_time = 2;
    builtin_interfaces.Duration estimated_time_remaining = 3;
    int32 number_of_recoveries = 4;
    float distance_remaining = 5;
  }

  message Result {
    NavigateToPoseErrorCode error_code = 1;
    string error_msg = 2;
  }
}

message NavigateThroughPosesAction {
  message Goal {
    repeated geometry_msgs.PoseStamped poses = 1;
    string behavior_tree = 2;
  }

  message Feedback {
    geometry_msgs.PoseStamped current_pose = 1;
    builtin_interfaces.Duration navigation_time = 2;
    builtin_interfaces.Duration estimated_time_remaining = 3;
    int32 number_of_recoveries = 4;
    float distance_remaining = 5;
    int32 number_of_poses_remaining = 6;
  }

  message Result {
    NavigateThroughPosesErrorCode error_code = 1;
    string error_msg = 2;
  }
}

message FollowPathAction {
  message Goal {
    planning_msgs.Path path = 1;
    string controller_id = 2;
    string goal_checker_id = 3;
    string progress_checker_id = 4;
  }

  message Feedback {
    float distance_to_goal = 1;
    float speed = 2;
  }

  message Result {
    FollowPathErrorCode error_code = 1;
    string error_msg = 2;
  }
}

message ComputePathToPoseAction {
  message Goal {
    geometry_msgs.PoseStamped goal = 1;
    geometry_msgs.PoseStamped start = 2;
    string planner_id = 3;
    bool use_start = 4;
  }

  message Feedback {}

  message Result {
    planning_msgs.Path path = 1;
    builtin_interfaces.Duration planning_time = 2;
    ComputePathToPoseErrorCode error_code = 3;
    string error_msg = 4;
  }
}

message ComputePathThroughPosesAction {
  message Goal {
    planning_msgs.Goals goals = 1;
    geometry_msgs.PoseStamped start = 2;
    string planner_id = 3;
    bool use_start = 4;
  }

  message Feedback {}

  message Result {
    planning_msgs.Path path = 1;
    builtin_interfaces.Duration planning_time = 2;
    ComputePathThroughPosesErrorCode error_code = 3;
    string error_msg = 4;
  }
}

message SmoothPathAction {
  message Goal {
    planning_msgs.Path path = 1;
    string smoother_id = 2;
    builtin_interfaces.Duration max_smoothing_duration = 3;
    bool check_for_collisions = 4;
  }

  message Feedback {}

  message Result {
    planning_msgs.Path path = 1;
    builtin_interfaces.Duration smoothing_duration = 2;
    bool was_completed = 3;
    SmoothPathErrorCode error_code = 4;
    string error_msg = 5;
  }
}

message FollowWaypointsAction {
  message Goal {
    uint32 number_of_loops = 1;
    uint32 goal_index = 2;
    repeated geometry_msgs.PoseStamped poses = 3;
  }

  message Feedback {
    uint32 current_waypoint = 1;
  }

  message Result {
    repeated WaypointStatus missed_waypoints = 1;
    FollowWaypointsErrorCode error_code = 2;
    string error_msg = 3;
  }
}

message SpinAction {
  message Goal {
    float target_yaw = 1;
    builtin_interfaces.Duration time_allowance = 2;
    bool disable_collision_checks = 3;
  }

  message Feedback {
    float angular_distance_traveled = 1;
  }

  message Result {
    builtin_interfaces.Duration total_elapsed_time = 1;
    SpinErrorCode error_code = 2;
    string error_msg = 3;
  }
}

message BackUpAction {
  message Goal {
    geometry_msgs.Point target = 1;
    float speed = 2;
    builtin_interfaces.Duration time_allowance = 3;
    bool disable_collision_checks = 4;
  }

  message Feedback {
    float distance_traveled = 1;
  }

  message Result {
    builtin_interfaces.Duration total_elapsed_time = 1;
    BackUpErrorCode error_code = 2;
    string error_msg = 3;
  }
}

message DriveOnHeadingAction {
  message Goal {
    geometry_msgs.Point target = 1;
    float speed = 2;
    builtin_interfaces.Duration time_allowance = 3;
    bool disable_collision_checks = 4;
  }

  message Feedback {
    float distance_traveled = 1;
  }

  message Result {
    builtin_interfaces.Duration total_elapsed_time = 1;
    DriveOnHeadingErrorCode error_code = 2;
    string error_msg = 3;
  }
}

message WaitAction {
  message Goal {
    builtin_interfaces.Duration time = 1;
  }

  message Feedback {
    builtin_interfaces.Duration time_left = 1;
  }

  message Result {
    builtin_interfaces.Duration total_elapsed_time = 1;
    WaitErrorCode error_code = 2;
    string error_msg = 3;
  }
}

message AssistedTeleopAction {
  message Goal {
    builtin_interfaces.Duration time_allowance = 1;
  }

  message Feedback {
    builtin_interfaces.Duration current_teleop_duration = 1;
  }

  message Result {
    builtin_interfaces.Duration total_elapsed_time = 1;
    AssistedTeleopErrorCode error_code = 2;
    string error_msg = 3;
  }
}

message DummyBehaviorAction {
  message Goal {
    string command = 1;
  }

  message Result {
    builtin_interfaces.Duration total_elapsed_time = 1;
    uint32 error_code = 2;
    string error_msg = 3;
  }
}
