// Copyright 2025 The Openbot Authors (duyongquan)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package autonomy.tasks.proto;

// Lua: tasks.navigate_to_pose
message NavigateToPoseNavigator {
  optional bool enable = 1;
  string default_behavior_tree_file = 2;
  string goal_blackboard_key = 3;
  string path_blackboard_key = 4;
}

// Lua: tasks.navigate_through_poses
message NavigateThroughPosesNavigator {
  optional bool enable = 1;
  string default_behavior_tree_file = 2;
  string goals_blackboard_key = 3;
  string path_blackboard_key = 4;
}

message TaskOptions {
  string global_frame = 1;
  string robot_base_frame = 2;
  string odom_topic = 3;
  uint32 bt_loop_duration = 4;
  double filter_duration = 5;
  uint32 default_server_timeout = 6;
  double local_survival_timeout = 7;
  repeated string navigators = 8;
  NavigateToPoseNavigator navigate_to_pose = 9;
  NavigateThroughPosesNavigator navigate_through_poses = 10;
  repeated string plugin_lib_names = 11;
  string plugin_lib_path = 12;
  string default_planner_id = 13;
  string default_controller_id = 14;
  string default_goal_checker_id = 15;
  double goal_reached_tolerance = 16;
  optional bool enable_autolink_action_servers = 17;
}
