// Copyright 2026 The Openbot Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package autonomy.localization.atla2.proto;

import "automsgs/msgs/sensor_msgs/camera_info.proto";
import "automsgs/msgs/sensor_msgs/compressed_image.proto";
import "automsgs/msgs/sensor_msgs/image.proto";
import "automsgs/msgs/sensor_msgs/imu.proto";
import "automsgs/msgs/std_msgs/header.proto";
import "common/fusion_style.proto";
import "sensor/barometer_sample.proto";
import "sensor/gps_sample.proto";
import "sensor/lidar_scan.proto";
import "sensor/optical_flow_sample.proto";

// LIVO input: vision + lidar + IMU (+ optional aids).
message LivoInput {
  automsgs.msgs.std_msgs.Header header = 1;
  FusionStyle fusion = 2;

  automsgs.msgs.sensor_msgs.Image image = 3;
  automsgs.msgs.sensor_msgs.CompressedImage image_compressed = 4;
  automsgs.msgs.sensor_msgs.Image image_right = 5;
  automsgs.msgs.sensor_msgs.CameraInfo camera_info = 6;
  LidarScan scan = 7;
  repeated automsgs.msgs.sensor_msgs.Imu imu = 8;

  GpsSample gps = 9;
  BarometerSample barometer = 10;
  OpticalFlowSample optical_flow = 11;

  bool has_image_right = 12;
  bool has_gps = 13;
  bool has_baro = 14;
  bool has_optical_flow = 15;
}
