/*
 * Copyright 2026 The Openbot Authors
 */

#include "autonomy/manipulation/setup/setup_assistant_lite.hpp"

#include <fstream>
#include <regex>
#include <sstream>

#include "autonomy/common/logging.hpp"
#include "autonomy/manipulation/motion/collision/mesh_convex_decomposition.hpp"
#include "autonomy/manipulation/model/simple_robot_model.hpp"
#include "autonomy/manipulation/model/simple_robot_state.hpp"
#include "autolink/common/file.hpp"

namespace autonomy {
namespace manipulation {
namespace setup {
namespace {

std::string JoinPath(const std::string& dir, const std::string& rel) {
  if (dir.empty() || dir == ".") {
    return rel;
  }
  if (dir.back() == '/' || dir.back() == '\\') {
    return dir + rel;
  }
  return dir + "/" + rel;
}

std::string ExtractAttr(const std::string& tag, const std::string& attr) {
  const std::regex pattern(attr + R"regex(="([^"]*)")regex");
  std::smatch match;
  if (std::regex_search(tag, match, pattern) && match.size() > 1) {
    return match[1].str();
  }
  return {};
}

std::vector<std::string> FindMeshFilenames(const std::string& urdf_path) {
  std::vector<std::string> out;
  std::ifstream in(urdf_path);
  if (!in) {
    return out;
  }
  std::ostringstream buf;
  buf << in.rdbuf();
  const std::string xml = buf.str();
  const std::regex mesh_re(R"regex(<mesh\b([^>]*)/?>)regex");
  for (std::sregex_iterator it(xml.begin(), xml.end(), mesh_re), end; it != end;
       ++it) {
    std::string filename = ExtractAttr((*it)[1].str(), "filename");
    if (filename.rfind("package://", 0) == 0) {
      const auto slash = filename.find('/', 10);
      if (slash != std::string::npos) {
        filename = filename.substr(slash + 1);
      }
    }
    if (!filename.empty()) {
      out.push_back(filename);
    }
  }
  return out;
}

bool WriteTextFile(const std::string& path, const std::string& body,
                   std::string* error) {
  std::ofstream out(path);
  if (!out) {
    if (error) {
      *error = "cannot write " + path;
    }
    return false;
  }
  out << body;
  return true;
}

void WritePlannerConfFiles(const SetupRequest& req, SetupResult* result) {
  if (!result) {
    return;
  }
  const std::string group = req.planning_group.empty() ? "arm" : req.planning_group;

  {
    const std::string path = JoinPath(req.output_dir, "ompl_planning.conf");
    std::ostringstream body;
    body << "# Generated by setup_assistant_lite (MoveIt ompl_planning.yaml lite)\n"
         << "# Format: name  planner_id  planning_time_s  max_attempts  [goal_tol]  [lvs]\n"
         << group << "[RRTConnect]   RRTConnect  1.0  3  0.001  0.01\n"
         << group << "[RRT]          RRT         1.0  3  0.001  0.01\n"
         << group << "[RRTstar]      RRTstar     2.0  2  0.001  0.01\n"
         << group << "[KPIECE]       KPIECE      1.5  3  0.001  0.01\n"
         << group << "[PRM]          PRM         2.0  2  0.001  0.01\n"
         << group << "[BiTRRT]       BiTRRT      1.5  3  0.001  0.01\n"
         << group << "[EST]          EST         1.5  3  0.001  0.01\n";
    if (WriteTextFile(path, body.str(), &result->error)) {
      result->conf_written.push_back(path);
    }
  }
  {
    const std::string path = JoinPath(req.output_dir, "chomp_planning.conf");
    const std::string body =
        "# Generated by setup_assistant_lite\n"
        "max_iterations=50\n"
        "max_iterations_after_collision_free=5\n"
        "num_timesteps=30\n"
        "learning_rate=0.1\n"
        "smoothness_cost_weight=0.1\n"
        "smoothness_cost_velocity=0.0\n"
        "smoothness_cost_acceleration=1.0\n"
        "smoothness_cost_jerk=0.0\n"
        "obstacle_cost_weight=1.0\n"
        "min_clearance=0.05\n"
        "ridge_factor=1.0e-4\n"
        "joint_update_limit=0.1\n"
        "filter_update=true\n"
        "voxel_resolution=0.05\n"
        "voxel_padding=0.25\n"
        "voxel_margin=0.4\n"
        "trajectory_initialization_method=quintic\n"
        "enable_failure_recovery=true\n"
        "max_recovery_attempts=2\n"
        "planning_time_limit=5.0\n";
    if (WriteTextFile(path, body, &result->error)) {
      result->conf_written.push_back(path);
    }
  }
  {
    const std::string path = JoinPath(req.output_dir, "stomp_planning.conf");
    const std::string body =
        "# Generated by setup_assistant_lite\n"
        "num_iterations=10\n"
        "num_iterations_after_valid=2\n"
        "num_timesteps=20\n"
        "num_rollouts=10\n"
        "noise_stddev=0.05\n"
        "collision_penalty=10.0\n"
        "control_cost_weight=0.1\n"
        "exponentiated_cost_sensitivity=10.0\n"
        "planning_time_limit=5.0\n"
        "enable_failure_recovery=true\n"
        "max_recovery_attempts=2\n";
    if (WriteTextFile(path, body, &result->error)) {
      result->conf_written.push_back(path);
    }
  }
  {
    const std::string path = JoinPath(req.output_dir, "kinematics.pb.txt");
    std::ostringstream body;
    body << "# Generated by setup_assistant_lite\n"
         << "kinematics_solver: \"kdl\"\n"
         << "base_frame: \"" << req.base_frame << "\"\n"
         << "tip_frame: \"" << req.tip_frame << "\"\n";
    if (WriteTextFile(path, body.str(), &result->error)) {
      result->conf_written.push_back(path);
    }
  }
  {
    const std::string path = JoinPath(req.output_dir, "controllers.pb.txt");
    const std::string body =
        "# Generated by setup_assistant_lite\n"
        "controller_id: \"arm_controller\"\n"
        "trajectory_topic: \"/arm_controller/joint_trajectory\"\n"
        "use_joint_trajectory_controller: true\n"
        "joint_states_topic: \"/joint_states\"\n";
    if (WriteTextFile(path, body, &result->error)) {
      result->conf_written.push_back(path);
    }
  }
  {
    const std::string path = JoinPath(req.output_dir, "planners.pb.txt");
    std::ostringstream body;
    body << "# Generated by setup_assistant_lite\n"
         << "planner_id: \"" << req.pb.planner_id() << "\"\n"
         << "# Alternatives: pilz_{ptp,lin,circ,sequence} | ompl | chomp | stomp\n"
         << "adapters: \"time_parameterization\"\n"
         << "adapters: \"validate_path\"\n";
    if (WriteTextFile(path, body.str(), &result->error)) {
      result->conf_written.push_back(path);
    }
  }
  {
    const std::string path =
        JoinPath(req.output_dir, "constraint_samplers.plugins");
    const std::string body =
        "# Generated by setup_assistant_lite\n"
        "# Optional external ConstraintSamplerAllocator plugin paths.\n";
    if (WriteTextFile(path, body, &result->error)) {
      result->conf_written.push_back(path);
    }
  }
}

}  // namespace

SetupResult GenerateSetup(const SetupRequest& req) {
  SetupResult result;
  if (req.urdf_path.empty() || req.output_dir.empty()) {
    result.set_error("urdf_path and output_dir required");
    return result;
  }

  model::SimpleRobotModel model;
  if (!model.Load(req.urdf_path, req.srdf_path)) {
    result.set_error("failed to load URDF/SRDF");
    return result;
  }

  const std::string pb_path = JoinPath(req.output_dir, "manipulation.pb.txt");
  {
    std::ofstream out(pb_path);
    if (!out) {
      result.set_error("cannot write " + pb_path);
      return result;
    }
    out << "# Generated by setup_assistant_lite\n";
    out << "robot_description: \"" << req.urdf_path << "\"\n";
    if (!req.srdf_path.empty()) {
      out << "robot_description_semantic: \"" << req.srdf_path << "\"\n";
    }
    out << "planning_group: \"" << req.planning_group << "\"\n";
    out << "planner_id: \"" << req.pb.planner_id() << "\"\n";
    out << "kinematics_solver: \"kdl\"\n";
    out << "controller_id: \"arm_controller\"\n";
    out << "base_frame: \"" << req.base_frame << "\"\n";
    out << "tip_frame: \"" << req.tip_frame << "\"\n";
    out << "collision_detector: \"" << req.collision_detector << "\"\n";
    out << "planning_time_milliseconds: 2000\n";
    out << "max_velocity: 1.0\n";
    out << "max_acceleration: 2.0\n";
    out << "max_translational_velocity: 0.5\n";
    out << "max_translational_acceleration: 1.0\n";
    out << "max_translational_deceleration: 1.0\n";
    out << "max_rotational_velocity: 1.0\n";
    out << "adapters: \"fix_start_state_bounds\"\n";
    out << "adapters: \"fix_start_state_path_constraints\"\n";
    out << "adapters: \"dense_sample\"\n";
    out << "adapters: \"time_parameterization\"\n";
    out << "adapters: \"validate_path\"\n";
    out << "adapters: \"check_constraints\"\n";
    out << "max_planning_attempts: 3\n";
    out << "enable_scene_monitor: true\n";
    out << "occupancy_self_filter_padding: 0.08\n";
    out << "execution_deviation_tolerance: 0.0\n";
    out << "execution_effort_tolerance: 0.0\n";
    for (const auto& jn : model.GetJointNames(req.planning_group)) {
      out << "default_joints: \"" << jn << "\"\n";
    }
    if (model.GetJointNames(req.planning_group).empty()) {
      for (const auto& jn : model.GetJointNames("all")) {
        out << "default_joints: \"" << jn << "\"\n";
      }
    }
  }
  result.manipulation_pb_txt = pb_path;
  result.conf_written.push_back(pb_path);

  if (req.emit_planner_confs) {
    WritePlannerConfFiles(req, &result);
    if (!result.error.empty() && result.conf_written.size() <= 1) {
      return result;
    }
    result.error.clear();
  }

  if (req.emit_convexparts_templates) {
    const auto meshes = FindMeshFilenames(req.urdf_path);
    const std::string urdf_dir = autolink::common::GetDirName(req.urdf_path);
    for (const auto& rel : meshes) {
      const std::string mesh_path = JoinPath(urdf_dir, rel);
      result.mesh_paths_found.push_back(mesh_path);
      const std::string sidecar = mesh_path + ".convexparts";
      std::ifstream exists(sidecar);
      if (exists.good()) {
        continue;  // keep existing offline parts
      }
      if (collision::WriteConvexPartsSidecar(sidecar, {})) {
        result.convexparts_written.push_back(sidecar);
        AINFO << "setup: wrote empty convexparts template " << sidecar;
      }
    }
  }

  result.set_success(true);
  AINFO << "setup_assistant_lite wrote " << pb_path
        << " confs=" << result.conf_written.size()
        << " groups=" << model.GetJointNames("all").size()
        << " ee=" << model.EndEffectors().size()
        << " passive=" << model.PassiveJoints().size();
  return result;
}

}  // namespace setup
}  // namespace manipulation
}  // namespace autonomy
