/*
 * Copyright 2026 The Openbot Authors
 */

/**
 * @file rpc_teleop_handlers.hpp
 * @brief TeleopService RpcHandlers: Velocity (bidi), Drive/BackUp/Spin streams,
 *        Cancel/Pause/Resume, GetStatus.
 *
 * @details
 * Forwards to Context::teleop() (TeleopStub). Velocity uses GoalChannel topics
 * @c kTeleopGoal / @c kTeleopFeedback (`/autonomy/task/teleop/{goal,feedback}`);
 * relative Drive/BackUp/Spin use Action servers (@c kDriveOnHeadingActionName,
 * @c kBackUpActionName, @c kSpinActionName) via TeleopRelativeBackend.
 *
 * Types:
 * - RpcTeleopVelocityHandler — hand-rolled bidi class (SMART_PTR)
 * - RpcTeleopDriveOnHeadingHandler / RpcTeleopBackUpHandler / RpcTeleopSpinHandler — BRIDGE_STREAM
 * - RpcTeleopCancelHandler / RpcTeleopPauseHandler / RpcTeleopResumeHandler —
 *   BRIDGE_DECL + inline
 * - RpcTeleopGetStatusHandler — BRIDGE_GET GetSnapshot
 *
 * Invariants:
 * - Velocity is hand-rolled (session + OnReadsDone); other streams use
 *   StreamHandler + IsTeleopResponseTerminal.
 * - Cancel/Pause/Resume are BRIDGE_DECL with inline OnRequest (Pause/Resume
 *   validate stub return bool).
 * - Ownership: per-RPC handlers; TeleopStub owned by Context / CancelRegistry.
 * - Threading: gRPC CQ; relative actions run on WorkScheduler.
 *
 * @see TeleopStub
 * @see handler_templates.hpp
 */

#pragma once

#include "autonomy/bridge/grpc/handlers/handler_templates.hpp"
#include <automsgs/msgs/status_msgs/status_msgs.pb.h>
#include <automsgs/rpcs/teleop.pb.h>

namespace autonomy {
namespace bridge {
namespace grpc {
namespace handlers {

/**
 * @brief async_grpc Signature for TeleopService/Velocity (bidi streams).
 */
DEFINE_HANDLER_SIGNATURE(
    RpcTeleopVelocitySignature,
    autonomy::common::async_grpc::Stream<::automsgs::rpcs::teleop::VelocityRequest>,
    autonomy::common::async_grpc::Stream<::automsgs::rpcs::teleop::TeleopResponse>,
    "/automsgs.rpcs.teleop.TeleopService/Velocity")

/**
 * @brief Bidi Velocity — OnReadsDone + session state (not a stub-stream template).
 *
 * @details Each VelocityRequest is forwarded to TeleopStub::HandleVelocity;
 * when the client half-closes, OnReadsDone finishes the stream.
 * stream_finished_ guards against double Finish. Implementation bodies live
 * in rpc_teleop_handlers.cpp.
 *
 * @note Not generated by BRIDGE_STREAM because of bidi request stream semantics.
 * @warning Must not Finish twice; stream_finished_ is the only guard.
 * @see TeleopStub::HandleVelocity
 */
class RpcTeleopVelocityHandler
    : public autonomy::common::async_grpc::RpcHandler<RpcTeleopVelocitySignature>
{
public:
    /**
     * @brief Shared / weak / unique pointer aliases.
     */
    AUTONOMY_SMART_PTR_DEFINITIONS(RpcTeleopVelocityHandler)

    /**
     * @brief Forward one VelocityRequest into TeleopStub.
     *
     * @param[in] request VelocityRequest (twist / goal_id / command fields).
     */
    void OnRequest(
        const ::automsgs::rpcs::teleop::VelocityRequest& request) override;

    /**
     * @brief Client half-close: finish the response stream if not already done.
     */
    void OnReadsDone() override;

private:
    /**
     * @brief Guards against double Finish on the Velocity response stream.
     */
    bool stream_finished_{false};
};

/** @brief TeleopService/DriveOnHeading — relative Action stream. */
BRIDGE_STREAM(
    RpcTeleopDriveOnHeadingHandler, ::automsgs::rpcs::teleop::DriveOnHeadingRequest,
    autonomy::common::async_grpc::Stream<::automsgs::rpcs::teleop::TeleopResponse>,
    "/automsgs.rpcs.teleop.TeleopService/DriveOnHeading", &Context::teleop,
    &clients::TeleopStub::HandleDriveOnHeading, &IsTeleopResponseTerminal);

/** @brief TeleopService/BackUp — relative Action stream. */
BRIDGE_STREAM(
    RpcTeleopBackUpHandler, ::automsgs::rpcs::teleop::BackUpRequest,
    autonomy::common::async_grpc::Stream<::automsgs::rpcs::teleop::TeleopResponse>,
    "/automsgs.rpcs.teleop.TeleopService/BackUp", &Context::teleop,
    &clients::TeleopStub::HandleBackUp, &IsTeleopResponseTerminal);

/** @brief TeleopService/Spin — relative Action stream. */
BRIDGE_STREAM(
    RpcTeleopSpinHandler, ::automsgs::rpcs::teleop::SpinRequest,
    autonomy::common::async_grpc::Stream<::automsgs::rpcs::teleop::TeleopResponse>,
    "/automsgs.rpcs.teleop.TeleopService/Spin", &Context::teleop,
    &clients::TeleopStub::HandleSpin, &IsTeleopResponseTerminal);

/** @brief TeleopService/Cancel — CancelGoal then OkStatus(kCancelled). */
BRIDGE_DECL(RpcTeleopCancelHandler, ::automsgs::rpcs::teleop::GoalRequest,
                ::automsgs::rpcs::common::Status,
                "/automsgs.rpcs.teleop.TeleopService/Cancel");

/** @brief TeleopService/Pause — PauseGoal or INVALID_ARGUMENT. */
BRIDGE_DECL(RpcTeleopPauseHandler, ::automsgs::rpcs::teleop::GoalRequest,
                ::automsgs::rpcs::common::Status,
                "/automsgs.rpcs.teleop.TeleopService/Pause");

/** @brief TeleopService/Resume — ResumeGoal or INVALID_ARGUMENT. */
BRIDGE_DECL(RpcTeleopResumeHandler, ::automsgs::rpcs::teleop::GoalRequest,
                ::automsgs::rpcs::common::Status,
                "/automsgs.rpcs.teleop.TeleopService/Resume");

/** @brief TeleopService/GetStatus — TeleopStub::GetSnapshot. */
BRIDGE_GET(
    RpcTeleopGetStatusHandler, ::automsgs::rpcs::teleop::GetStatusRequest,
    ::automsgs::rpcs::teleop::TeleopResponse,
    "/automsgs.rpcs.teleop.TeleopService/GetStatus", &Context::teleop,
    &clients::TeleopStub::GetSnapshot);

/**
 * @brief Cancel OnRequest: CancelGoal(goal_id) then OkStatus(kCancelled).
 *
 * @param[in] request GoalRequest with optional goal_id filter.
 */
inline void RpcTeleopCancelHandler::OnRequest(
    const ::automsgs::rpcs::teleop::GoalRequest& request) {
    ReplyStatusWithContext(this, [&](auto* context) {
        context->teleop().CancelGoal(request.goal_id());
        return OkStatus(kCancelled);
    });
}

/**
 * @brief Pause OnRequest: PauseGoal or INVALID_ARGUMENT("nothing to pause").
 *
 * @param[in] request GoalRequest with optional goal_id filter.
 */
inline void RpcTeleopPauseHandler::OnRequest(
    const ::automsgs::rpcs::teleop::GoalRequest& request) {
    ReplyStatusWithContext(this, [&](auto* context) {
        return context->teleop().PauseGoal(request.goal_id())
                   ? OkStatus(kPaused)
                   : ErrorStatus(
                         ::automsgs::msgs::status_msgs::INVALID_ARGUMENT,
                         "nothing to pause");
    });
}

/**
 * @brief Resume OnRequest: ResumeGoal or INVALID_ARGUMENT("nothing to resume").
 *
 * @param[in] request GoalRequest with optional goal_id filter.
 */
inline void RpcTeleopResumeHandler::OnRequest(
    const ::automsgs::rpcs::teleop::GoalRequest& request) {
    ReplyStatusWithContext(this, [&](auto* context) {
        return context->teleop().ResumeGoal(request.goal_id())
                   ? OkStatus(kResumed)
                   : ErrorStatus(
                         ::automsgs::msgs::status_msgs::INVALID_ARGUMENT,
                         "nothing to resume");
    });
}

}  // namespace handlers
}  // namespace grpc
}  // namespace bridge
}  // namespace autonomy
