# Normal filter comparison (area vs raster).
- name: surface_normals_area
  type: NormalVectorsFilter
  params:
    input_layer: elevation_filtered
    algorithm: area
    output_layers_prefix: normal_area_
    radius: 0.05
    normal_vector_positive_axis: z
    parallelization_enabled: true
    thread_number: 4

- name: surface_normals_raster
  type: NormalVectorsFilter
  params:
    input_layer: elevation_filtered
    algorithm: raster
    output_layers_prefix: normal_raster_
    normal_vector_positive_axis: z
    parallelization_enabled: true
    thread_number: 4
