// Copyright 2025 The Openbot Authors （duyongquan）
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package automsgs.msgs.stereo_msgs;

import "automsgs/msgs/std_msgs/header.proto";
import "automsgs/msgs/sensor_msgs/image.proto";
import "automsgs/msgs/sensor_msgs/region_of_interest.proto";

// Floating point disparity image with stereo geometry.
message DisparityImage {
  // Separate header for compatibility with TimeSynchronizer.
  automsgs.msgs.std_msgs.Header header = 1;

  // Disparity image, adjusted for principal point offsets.
  automsgs.msgs.sensor_msgs.Image image = 2;

  // Stereo geometry: depth Z = f * T / d.
  float f = 3; // focal length in pixels
  float t = 4; // baseline in world units

  // Subwindow of potentially valid disparity values.
  automsgs.msgs.sensor_msgs.RegionOfInterest valid_window = 5;

  // Range of disparities searched.
  float min_disparity = 6;
  float max_disparity = 7;

  // Smallest allowed disparity increment.
  float delta_d = 8;
}

