load(
    "//tools:package.bzl",
    "autonomy_cc_library",
)

package(default_visibility = ["//visibility:public"])

autonomy_cc_library(
    name = "autonomy_map",
    srcs = [
        "common/costmap_bridge.cpp",
        "common/map_interface.cpp",
        "common/rolling_grid_3d.cpp",
        "costmap_2d/array_parser.cpp",
        "costmap_2d/costmap_2d.cpp",
        "costmap_2d/costmap_2d_publisher.cpp",
        "costmap_2d/costmap_2d_wrapper.cpp",
        "costmap_2d/costmap_layer.cpp",
        "costmap_2d/costmap_math.cpp",
        "costmap_2d/costmap_topic_collision_checker.cpp",
        "costmap_2d/filters/binary_filter.cpp",
        "costmap_2d/filters/costmap_filter.cpp",
        "costmap_2d/filters/keepout_filter.cpp",
        "costmap_2d/filters/speed_filter.cpp",
        "costmap_2d/footprint.cpp",
        "costmap_2d/footprint_collision_checker.cpp",
        "costmap_2d/footprint_subscriber.cpp",
        "costmap_2d/layer.cpp",
        "costmap_2d/layered_costmap.cpp",
        "costmap_2d/layers/denoise_layer.cpp",
        "costmap_2d/layers/inflation_layer.cpp",
        "costmap_2d/layers/obstacle_layer.cpp",
        "costmap_2d/layers/range_sensor_layer.cpp",
        "costmap_2d/layers/static_layer.cpp",
        "costmap_2d/layers/voxel_layer.cpp",
        "costmap_2d/map_io.cpp",
        "costmap_2d/map_mode.cpp",
        "costmap_2d/map_saver.cpp",
        "costmap_2d/observation_buffer.cpp",
        "costmap_2d/utils/robot_utils.cpp",
        "grid_map/grid_map_core/buffer_region.cpp",
        "grid_map/grid_map_core/cubic_interpolation.cpp",
        "grid_map/grid_map_core/grid_map.cpp",
        "grid_map/grid_map_core/grid_map_math.cpp",
        "grid_map/grid_map_core/iterators/circle_iterator.cpp",
        "grid_map/grid_map_core/iterators/ellipse_iterator.cpp",
        "grid_map/grid_map_core/iterators/grid_map_iterator.cpp",
        "grid_map/grid_map_core/iterators/line_iterator.cpp",
        "grid_map/grid_map_core/iterators/polygon_iterator.cpp",
        "grid_map/grid_map_core/iterators/sliding_window_iterator.cpp",
        "grid_map/grid_map_core/iterators/spiral_iterator.cpp",
        "grid_map/grid_map_core/iterators/submap_iterator.cpp",
        "grid_map/grid_map_core/polygon.cpp",
        "grid_map/grid_map_core/submap_geometry.cpp",
        "grid_map/grid_map_core/test_helpers.cpp",
        "grid_map/grid_map_cv/grid_map_cv_processing.cpp",
        "grid_map/grid_map_cv/inpaint_filter.cpp",
        "grid_map/grid_map_filters/buffer_normalizer_filter.cpp",
        "grid_map/grid_map_filters/color_blending_filter.cpp",
        "grid_map/grid_map_filters/color_fill_filter.cpp",
        "grid_map/grid_map_filters/color_map_filter.cpp",
        "grid_map/grid_map_filters/curvature_filter.cpp",
        "grid_map/grid_map_filters/deletion_filter.cpp",
        "grid_map/grid_map_filters/duplication_filter.cpp",
        "grid_map/grid_map_filters/filter_factory.cpp",
        "grid_map/grid_map_filters/light_intensity_filter.cpp",
        "grid_map/grid_map_filters/math_expression_filter.cpp",
        "grid_map/grid_map_filters/mean_in_radius_filter.cpp",
        "grid_map/grid_map_filters/median_fill_filter.cpp",
        "grid_map/grid_map_filters/min_in_radius_filter.cpp",
        "grid_map/grid_map_filters/mock_filter.cpp",
        "grid_map/grid_map_filters/normal_color_map_filter.cpp",
        "grid_map/grid_map_filters/normal_vectors_filter.cpp",
        "grid_map/grid_map_filters/set_basic_layers_filter.cpp",
        "grid_map/grid_map_filters/sliding_window_math_expression_filter.cpp",
        "grid_map/grid_map_filters/threshold_filter.cpp",
        "grid_map/grid_map_loader/grid_map_loader.cpp",
        "grid_map/grid_map_msgs/grid_map_converter.cpp",
        "grid_map/grid_map_pcl/grid_map_pcl_converter.cpp",
        "grid_map/grid_map_pcl/grid_map_pcl_loader.cpp",
        "grid_map/grid_map_pcl/helpers.cpp",
        "grid_map/grid_map_pcl/pcl_loader_parameters.cpp",
        "grid_map/grid_map_pcl/pcl_test_helpers.cpp",
        "grid_map/grid_map_pcl/pointcloud_processor.cpp",
        "grid_map/grid_map_sdf/signed_distance_2d.cpp",
        "grid_map/grid_map_sdf/signed_distance_field.cpp",
        "grid_map/grid_map_wrapper.cpp",
        "map_options.cpp",
        "map_server.cpp",
        "utils/data_loader_utils.cpp",
        "utils/pgm_converter.cpp",
    ],
    hdrs = [
        "common/costmap_bridge.hpp",
        "common/grid_3d.hpp",
        "common/map_interface.hpp",
        "common/rolling_grid_3d.hpp",
        "constants.hpp",
        "costmap_2d/array_parser.hpp",
        "costmap_2d/cost_values.hpp",
        "costmap_2d/costmap_2d.hpp",
        "costmap_2d/costmap_2d_publisher.hpp",
        "costmap_2d/costmap_2d_wrapper.hpp",
        "costmap_2d/costmap_layer.hpp",
        "costmap_2d/costmap_math.hpp",
        "costmap_2d/costmap_topic_collision_checker.hpp",
        "costmap_2d/denoise/image.hpp",
        "costmap_2d/denoise/image_processing.hpp",
        "costmap_2d/exceptions.hpp",
        "costmap_2d/filters/binary_filter.hpp",
        "costmap_2d/filters/costmap_filter.hpp",
        "costmap_2d/filters/filter_values.hpp",
        "costmap_2d/filters/keepout_filter.hpp",
        "costmap_2d/filters/speed_filter.hpp",
        "costmap_2d/footprint.hpp",
        "costmap_2d/footprint_collision_checker.hpp",
        "costmap_2d/footprint_subscriber.hpp",
        "costmap_2d/layer.hpp",
        "costmap_2d/layered_costmap.hpp",
        "costmap_2d/layers/denoise_layer.hpp",
        "costmap_2d/layers/inflation_layer.hpp",
        "costmap_2d/layers/obstacle_layer.hpp",
        "costmap_2d/layers/range_sensor_layer.hpp",
        "costmap_2d/layers/static_layer.hpp",
        "costmap_2d/layers/voxel_layer.hpp",
        "costmap_2d/map_io.hpp",
        "costmap_2d/map_mode.hpp",
        "costmap_2d/map_saver.hpp",
        "costmap_2d/observation.hpp",
        "costmap_2d/observation_buffer.hpp",
        "costmap_2d/utils/geometry_utils.hpp",
        "costmap_2d/utils/line_iterator.hpp",
        "costmap_2d/utils/occ_grid_values.hpp",
        "costmap_2d/utils/odometry_utils.hpp",
        "costmap_2d/utils/robot_utils.hpp",
        "costmap_2d/utils/validate_messages.hpp",
        "costmap_2d/voxel_grid.hpp",
        "grid_map/grid_map_core/buffer_region.hpp",
        "grid_map/grid_map_core/cubic_interpolation.hpp",
        "grid_map/grid_map_core/eigen_plugins/dense_base_plugin.hpp",
        "grid_map/grid_map_core/eigen_plugins/functors.hpp",
        "grid_map/grid_map_core/eigen_plugins/functors_plugin.hpp",
        "grid_map/grid_map_core/grid_map.hpp",
        "grid_map/grid_map_core/grid_map_core.hpp",
        "grid_map/grid_map_core/grid_map_math.hpp",
        "grid_map/grid_map_core/gtest_eigen.hpp",
        "grid_map/grid_map_core/iterators/circle_iterator.hpp",
        "grid_map/grid_map_core/iterators/ellipse_iterator.hpp",
        "grid_map/grid_map_core/iterators/grid_map_iterator.hpp",
        "grid_map/grid_map_core/iterators/iterators.hpp",
        "grid_map/grid_map_core/iterators/line_iterator.hpp",
        "grid_map/grid_map_core/iterators/polygon_iterator.hpp",
        "grid_map/grid_map_core/iterators/sliding_window_iterator.hpp",
        "grid_map/grid_map_core/iterators/spiral_iterator.hpp",
        "grid_map/grid_map_core/iterators/submap_iterator.hpp",
        "grid_map/grid_map_core/polygon.hpp",
        "grid_map/grid_map_core/submap_geometry.hpp",
        "grid_map/grid_map_core/test_helpers.hpp",
        "grid_map/grid_map_core/type_defs.hpp",
        "grid_map/grid_map_core/utils/testing.hpp",
        "grid_map/grid_map_costmap_2d/costmap_2d_converter.hpp",
        "grid_map/grid_map_costmap_2d/grid_map_costmap_2d.hpp",
        "grid_map/grid_map_cv/grid_map_cv.hpp",
        "grid_map/grid_map_cv/grid_map_cv_converter.hpp",
        "grid_map/grid_map_cv/grid_map_cv_processing.hpp",
        "grid_map/grid_map_cv/inpaint_filter.hpp",
        "grid_map/grid_map_filters/buffer_normalizer_filter.hpp",
        "grid_map/grid_map_filters/color_blending_filter.hpp",
        "grid_map/grid_map_filters/color_fill_filter.hpp",
        "grid_map/grid_map_filters/color_map_filter.hpp",
        "grid_map/grid_map_filters/curvature_filter.hpp",
        "grid_map/grid_map_filters/deletion_filter.hpp",
        "grid_map/grid_map_filters/duplication_filter.hpp",
        "grid_map/grid_map_filters/eigen_lab/EigenLab.h",
        "grid_map/grid_map_filters/filter_factory.hpp",
        "grid_map/grid_map_filters/filters/filter_base.hpp",
        "grid_map/grid_map_filters/filters/filter_chain.hpp",
        "grid_map/grid_map_filters/grid_map_filters.hpp",
        "grid_map/grid_map_filters/light_intensity_filter.hpp",
        "grid_map/grid_map_filters/math_expression_filter.hpp",
        "grid_map/grid_map_filters/mean_in_radius_filter.hpp",
        "grid_map/grid_map_filters/median_fill_filter.hpp",
        "grid_map/grid_map_filters/min_in_radius_filter.hpp",
        "grid_map/grid_map_filters/mock_filter.hpp",
        "grid_map/grid_map_filters/normal_color_map_filter.hpp",
        "grid_map/grid_map_filters/normal_vectors_filter.hpp",
        "grid_map/grid_map_filters/set_basic_layers_filter.hpp",
        "grid_map/grid_map_filters/sliding_window_math_expression_filter.hpp",
        "grid_map/grid_map_filters/threshold_filter.hpp",
        "grid_map/grid_map_loader/grid_map_loader.hpp",
        "grid_map/grid_map_msgs/grid_map.hpp",
        "grid_map/grid_map_msgs/grid_map_converter.hpp",
        "grid_map/grid_map_msgs/msg_helpers.hpp",
        "grid_map/grid_map_pcl/grid_map_pcl.hpp",
        "grid_map/grid_map_pcl/grid_map_pcl_converter.hpp",
        "grid_map/grid_map_pcl/grid_map_pcl_loader.hpp",
        "grid_map/grid_map_pcl/helpers.hpp",
        "grid_map/grid_map_pcl/pcl_loader_parameters.hpp",
        "grid_map/grid_map_pcl/pcl_test_helpers.hpp",
        "grid_map/grid_map_pcl/pointcloud_processor.hpp",
        "grid_map/grid_map_sdf/distance_derivatives.hpp",
        "grid_map/grid_map_sdf/grid_map_sdf.hpp",
        "grid_map/grid_map_sdf/gridmap_3d_lookup.hpp",
        "grid_map/grid_map_sdf/naive_signed_distance.hpp",
        "grid_map/grid_map_sdf/pixel_border_distance.hpp",
        "grid_map/grid_map_sdf/signed_distance_2d.hpp",
        "grid_map/grid_map_sdf/signed_distance_field.hpp",
        "grid_map/grid_map_sdf/utils.hpp",
        "grid_map/grid_map_wrapper.hpp",
        "map_options.hpp",
        "map_server.hpp",
        "utils/data_loader_utils.hpp",
        "utils/decompose/data_type.hpp",
        "utils/decompose/data_utils.hpp",
        "utils/decompose/decomp_base.hpp",
        "utils/decompose/ellipsoid.hpp",
        "utils/decompose/ellipsoid_decomp.hpp",
        "utils/decompose/geometric_utils.hpp",
        "utils/decompose/iterative_decomp.hpp",
        "utils/decompose/line_segment.hpp",
        "utils/decompose/polyhedron.hpp",
        "utils/decompose/seed_decomp.hpp",
        "utils/pgm_converter.hpp",
    ],
    copts = ['-DMODULE_NAME=\"map\"'],
    include_prefix = "autonomy/map",
    deps = [
        "//autonomy/common:autonomy_common",
        "//autonomy/transform:autonomy_transform",
        "//:automsgs",
        "//:autonomy_headers",
        "@eigen//:eigen",
        "@com_github_google_glog//:glog",
        "@com_google_protobuf//:protobuf",
        "//:pthread",
    ],
)

filegroup(
    name = "runtime_data",
    srcs = glob(
        [
            "conf/**",
            "dag/**",
            "launch/**",
        ],
        allow_empty = True,
    ),
)
