// Copyright 2026 The Openbot Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package autonomy.localization.atla2.proto;

import "automsgs/msgs/std_msgs/header.proto";
import "common/degradation_level.proto";
import "common/frontend_mode.proto";

// Sensor health + recommended degradation (fusion/degradation).
message HealthReport {
  automsgs.msgs.std_msgs.Header header = 1;
  bool image_ok = 2;
  bool lidar_ok = 3;
  bool imu_ok = 4;
  bool gps_ok = 5;
  bool baro_ok = 6;
  DegradationLevel level = 7;
  FrontendMode recommended_mode = 8;
  double covariance_trace = 9;
}
