# Pin protobuf to 3.19.x installed under /usr/local.
# gRPC or system packages may install protobuf 4.x+ headers that are
# incompatible with code generated by older protoc binaries.

if(AUTONOMY_PROTOBUF319_CONFIGURED)
  return()
endif()
set(AUTONOMY_PROTOBUF319_CONFIGURED TRUE)

list(PREPEND CMAKE_PREFIX_PATH "/usr/local")
set(Protobuf_ROOT "/usr/local" CACHE PATH "Protobuf 3.19 install prefix")

find_program(_AUTONOMY_PROTOC NAMES protoc
  HINTS /usr/local/bin
  NO_DEFAULT_PATH
)
if(NOT _AUTONOMY_PROTOC)
  find_program(_AUTONOMY_PROTOC NAMES protoc)
endif()

find_package(Protobuf REQUIRED)

if(Protobuf_VERSION VERSION_LESS "3.19.0"
    OR Protobuf_VERSION VERSION_GREATER_EQUAL "3.20.0")
  message(FATAL_ERROR
    "Protobuf 3.19.x is required (found ${Protobuf_VERSION}). "
    "Run: bash src/autonomy/docker/install/install_protobuf.sh")
endif()

if(_AUTONOMY_PROTOC)
  set(Protobuf_PROTOC_EXECUTABLE "${_AUTONOMY_PROTOC}"
    CACHE FILEPATH "protoc executable" FORCE)
endif()

if(NOT Protobuf_PROTOC_EXECUTABLE)
  message(FATAL_ERROR
    "protoc not found. Run: bash src/autonomy/docker/install/install_protobuf.sh")
endif()

execute_process(
  COMMAND "${Protobuf_PROTOC_EXECUTABLE}" --version
  OUTPUT_VARIABLE _protoc_version_out
  ERROR_VARIABLE _protoc_version_err
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_STRIP_TRAILING_WHITESPACE
)
set(_protoc_version "${_protoc_version_out}${_protoc_version_err}")
if(NOT _protoc_version MATCHES "3\\.19\\.")
  message(FATAL_ERROR
    "protoc 3.19.x is required (got '${_protoc_version}'). "
    "Run: bash src/autonomy/docker/install/install_protobuf.sh")
endif()

message(STATUS "Using Protobuf ${Protobuf_VERSION} includes: ${Protobuf_INCLUDE_DIRS}")
message(STATUS "Using protoc: ${Protobuf_PROTOC_EXECUTABLE} (${_protoc_version})")
