"""Bazel tools for Autonomy (Apollo tools/ counterpart)."""

package(default_visibility = ["//visibility:public"])

exports_files([
    "package.bzl",
    "common.bzl",
    "dependencies.bzl",
    "repositories.bzl",
    "prefix.BUILD",
    "prefix_stub.BUILD",
    "opencv.BUILD",
    "opencv_stub.BUILD",
    "bazel.rc",
    "generate_autonomy_protos.sh",
    "autonomy_proto_files.bzl",
])
