// Copyright 2025 The Openbot Authors （duyongquan）
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package autonomy.tasks.behavior_tree.proto;

import "autonomy/commsgs/proto/std_msgs.proto";
import "autonomy/commsgs/proto/geometry_msgs.proto";
import "autonomy/commsgs/proto/builtin_interfaces.proto";

message BehaviorTreeStatusChange
{
    // internal behavior tree event timestamp. Typically this is wall clock time
    autonomy.commsgs.proto.builtin_interfaces.Time timestamp = 1;  
    string node_name = 2;

    // unique ID for this node
    uint32 uid = 3;

    // previous status IDLE, RUNNING, SUCCESS or FAILURE
    string previous_status = 4;

    // current status IDLE, RUNNING, SUCCESS or FAILURE
    string current_status = 5;
}

message BehaviorTreeLog
{
    // ROS time that this log message was sent.
    autonomy.commsgs.proto.builtin_interfaces.Time timestamp = 1;

    // event log
    repeated BehaviorTreeStatusChange event_log = 2;
}

message CollisionDetectorState
{
    // Name of configured polygons
    repeated string polygons = 1;

    // List of detections for each polygon
    repeated bool detections = 2;
}

// Action type for robot in Collision Monitor
enum CollisionMonitorActionType
{
    COLLISION_MONITOR_DO_NOTHING = 0; // No action
    COLLISION_MONITOR_STOP = 1; // Stop the robot
    COLLISION_MONITOR_SLOWDOWN = 2; // Slowdown in percentage from current operating speed
    COLLISION_MONITOR_APPROACH = 3; // Keep constant time interval before collision
    COLLISION_MONITOR_LIMIT = 4; // Sets a limit of velocities if pts in range
}

message CollisionMonitorState
{
    // Action type for robot in Collision Monitor
    CollisionMonitorActionType action_type = 1;

    // Name of triggered polygon
    string polygon_name = 2;
}

// This represents a 2-D grid map, in which each cell has an associated cost
message Costmap
{
    autonomy.commsgs.proto.std_msgs.Header header = 1;

    // MetaData for the map
    CostmapMetaData metadata = 2;

    // The cost data, in row-major order, starting with (0,0).
    repeated uint32 data = 3;
}

message CostmapFilterInfo
{
    autonomy.commsgs.proto.std_msgs.Header header = 1;
    
    // Type of plugin used (keepout filter, speed limit in m/s, speed limit in percent, etc...)
    // 0: keepout/lanes filter
    // 1: speed limit filter in % of maximum speed
    // 2: speed limit filter in absolute values (m/s)
    uint32 type = 2;
    
    // Name of filter mask topic
    string filter_mask_topic = 3;
    
    // Multiplier base offset and multiplier coefficient for conversion of OccGrid.
    // Used to convert OccupancyGrid data values to filter space values.
    // data -> into some other number space:
    // space = data * multiplier + base
    float base = 4;
    float multiplier = 5;
}

message CostmapMetaData
{
    // This hold basic information about the characteristics of the Costmap

    // The time at which the static map was loaded
    autonomy.commsgs.proto.builtin_interfaces.Time map_load_time = 1;

    // The time of the last update to costmap
    autonomy.commsgs.proto.builtin_interfaces.Time update_time = 2;

    // The corresponding layer name
    string layer = 3;

    // The map resolution [m/cell]
    float resolution = 4;

    // Number of cells in the horizontal direction
    uint32 size_x = 5;

    // Number of cells in the vertical direction
    uint32 size_y = 6;

    // The origin of the costmap [m, m, rad].
    // This is the real-world pose of the cell (0,0) in the map.
    autonomy.commsgs.proto.geometry_msgs.Pose origin = 7;
}

message CostmapUpdate
{
    // Update msg for Costmap containing the modified part of Costmap
    autonomy.commsgs.proto.std_msgs.Header header = 1;

    uint32 x = 2;
    uint32 y = 3;

    uint32 size_x = 4;
    uint32 size_y = 5;

    // The cost data, in row-major order, starting with (x,y) from 0-255 in Costmap format rather than OccupancyGrid 0-100.
    repeated uint32 data = 6;
}

// Edge cost to use with nav2_msgs/srv/DynamicEdges to adjust route edge costs
message EdgeCost
{
    uint32 edgeid = 1;
    float cost = 2;
}

// This represents an individual particle with weight produced by a particle filter
message Particle
{
    autonomy.commsgs.proto.geometry_msgs.Pose pose = 1;

    double weight = 2;
}

// This represents a particle cloud containing particle poses and weights
message ParticleCloud
{
    autonomy.commsgs.proto.std_msgs.Header header = 1;

    // Array of particles in the cloud
    repeated Particle particles = 2;
}

message Route
{
    autonomy.commsgs.proto.std_msgs.Header header = 1;
    float route_cost = 2;
    repeated RouteNode nodes = 3; // ordered set of nodes of the route
    repeated RouteEdge edges = 4; // ordered set of edges that connect nodes
}

message RouteEdge
{
    uint32 edgeid = 1;
    autonomy.commsgs.proto.geometry_msgs.Point start = 2;
    autonomy.commsgs.proto.geometry_msgs.Point end = 3;
}

message RouteNode
{
    uint32 nodeid = 1;
    autonomy.commsgs.proto.geometry_msgs.Point position = 2;
}

message SpeedLimit
{
    autonomy.commsgs.proto.std_msgs.Header header = 1;
    
    // Setting speed limit in percentage if true or in absolute values in false case
    bool percentage = 2;
    
    // Maximum allowed speed (in percent of maximum robot speed or in m/s depending
    // on "percentage" value). When no-limit it is set to 0.0
    double speed_limit = 3;
}

//  An array of trajectory points that represents a trajectory for a robot to follow.
message Trajectory
{
    // Indicates the frame_id of the trajectory.
    autonomy.commsgs.proto.std_msgs.Header header = 1;

    // Array of trajectory points to follow.
    repeated TrajectoryPoint points = 2;
}

// Trajectory point state
message TrajectoryPoint
{
    // Desired time from the trajectory start to arrive at this trajectory sample.
    autonomy.commsgs.proto.builtin_interfaces.Duration time_from_start = 1;

    // Pose of the trajectory sample.
    autonomy.commsgs.proto.geometry_msgs.Pose pose = 2;

    // Velocity of the trajectory sample.
    autonomy.commsgs.proto.geometry_msgs.Twist velocity = 3;

    // Acceleration of the trajectory (optional).
    autonomy.commsgs.proto.geometry_msgs.Accel acceleration = 4;

    // Force/Torque to apply at trajectory sample (optional).
    autonomy.commsgs.proto.geometry_msgs.Wrench effort = 5;
}

message VoxelGrid
{
    autonomy.commsgs.proto.std_msgs.Header header = 1;
    repeated uint32 data = 2;
    autonomy.commsgs.proto.geometry_msgs.Point32 origin = 3;
    autonomy.commsgs.proto.geometry_msgs.Vector3 resolutions = 4;
    uint32 size_x = 5;
    uint32 size_y = 6;
    uint32 size_z = 7;
}

// Waypoint state for multi-goal navigation or waypoint following
enum WaypointStatusType
{
    WAYPOINT_STATUS_PENDING = 0; // Waypoint is not processed or processing
    WAYPOINT_STATUS_COMPLETED = 1; // Waypoint is completed
    WAYPOINT_STATUS_SKIPPED = 2; // Waypoint is skipped
    WAYPOINT_STATUS_FAILED = 3; // Waypoint is failed
}

message WaypointStatus
{
    WaypointStatusType waypoint_status = 1;
    uint32 waypoint_index = 2;
    autonomy.commsgs.proto.geometry_msgs.PoseStamped waypoint_pose = 3;
    uint32 error_code = 4;
    string error_msg = 5;
}
