# External package discovery derived from enabled Autonomy domains.

include_guard(GLOBAL)

if(NOT DEFINED AUTONOMY_BUILD_COMMON_OSQP)
  option(AUTONOMY_BUILD_COMMON_OSQP
    "Build the OSQP-backed common MPC library" ON)
endif()

function(autonomy_collect_required_package_groups _out_variable)
  set(_groups "")
  if("common" IN_LIST AUTONOMY_ENABLED_MODULES)
    list(APPEND _groups core common_math)
    if(AUTONOMY_BUILD_COMMON_OSQP)
      list(APPEND _groups osqp)
    endif()
  endif()
  if("map" IN_LIST AUTONOMY_ENABLED_MODULES
      OR "localization" IN_LIST AUTONOMY_ENABLED_MODULES
      OR "perception" IN_LIST AUTONOMY_ENABLED_MODULES
      OR ((BUILD_ONNXRUNTIME OR BUILD_TENSORRT)
          AND "common" IN_LIST AUTONOMY_ENABLED_MODULES))
    list(APPEND _groups common_vision)
  endif()
  if("map" IN_LIST AUTONOMY_ENABLED_MODULES)
    list(APPEND _groups map)
  endif()
  if("control" IN_LIST AUTONOMY_ENABLED_MODULES)
    list(APPEND _groups control)
  endif()
  if("task" IN_LIST AUTONOMY_ENABLED_MODULES)
    list(APPEND _groups task)
  endif()
  if("localization" IN_LIST AUTONOMY_ENABLED_MODULES)
    list(APPEND _groups localization)
  endif()
  if(BUILD_GRPC AND "bridge" IN_LIST AUTONOMY_ENABLED_MODULES)
    list(APPEND _groups grpc)
  endif()
  if(BUILD_AUTOVIZ)
    list(APPEND _groups autoviz)
  endif()
  if(BUILD_PROMETHEUS AND "system" IN_LIST AUTONOMY_ENABLED_MODULES)
    list(APPEND _groups prometheus)
  endif()
  if(BUILD_SHERPA_ONNX AND "audio" IN_LIST AUTONOMY_ENABLED_MODULES)
    list(APPEND _groups sherpa_onnx)
  endif()
  if((BUILD_ONNXRUNTIME OR BUILD_TENSORRT)
      AND ("common" IN_LIST AUTONOMY_ENABLED_MODULES
           OR "perception" IN_LIST AUTONOMY_ENABLED_MODULES))
    list(APPEND _groups inference)
  endif()
  if("visualization" IN_LIST AUTONOMY_ENABLED_MODULES)
    list(APPEND _groups foxglove)
  endif()
  list(REMOVE_DUPLICATES _groups)
  set(${_out_variable} "${_groups}" PARENT_SCOPE)
endfunction()

function(autonomy_find_dependencies)
  autonomy_collect_required_package_groups(_required_groups)
  foreach(_group IN LISTS _required_groups)
    if(_group STREQUAL "core")
      find_package(Eigen3 REQUIRED)
      find_package(nlohmann_json REQUIRED)
      set(GFLAGS_USE_TARGET_NAMESPACE TRUE)
      find_package(gflags CONFIG REQUIRED)
      find_package(Glog REQUIRED)
      include(EnsureProtobuf319)
      find_package(yaml-cpp REQUIRED)
      find_package(Threads REQUIRED)
    elseif(_group STREQUAL "common_math")
      find_package(Ceres REQUIRED)
    elseif(_group STREQUAL "common_vision")
      find_package(OpenCV REQUIRED)
      if(NOT TARGET autonomy_opencv)
        add_library(autonomy_opencv INTERFACE)
        target_include_directories(autonomy_opencv SYSTEM INTERFACE
          $<BUILD_INTERFACE:${OpenCV_INCLUDE_DIRS}>)
        target_link_libraries(autonomy_opencv INTERFACE ${OpenCV_LIBS})
        add_library(autonomy::opencv ALIAS autonomy_opencv)
        set_property(GLOBAL APPEND
          PROPERTY AUTONOMY_MODULE_TARGETS autonomy_opencv)
      endif()
    elseif(_group STREQUAL "osqp")
      find_package(OSQP REQUIRED)
    elseif(_group STREQUAL "map")
      find_package(PCL REQUIRED COMPONENTS
        common features filters io kdtree segmentation surface)
      find_package(TBB REQUIRED)
      find_package(OpenMP QUIET)
    elseif(_group STREQUAL "control")
      find_package(Ipopt QUIET)
    elseif(_group STREQUAL "task")
      find_package(behaviortree_cpp REQUIRED)
    elseif(_group STREQUAL "localization")
      find_package(LuaGoogle REQUIRED)
      find_package(FBow REQUIRED)
      find_package(G2o REQUIRED)
      find_package(SQLite3 REQUIRED)
      find_package(Boost REQUIRED COMPONENTS iostreams)
      find_package(PkgConfig REQUIRED)
      pkg_check_modules(CAIRO REQUIRED IMPORTED_TARGET cairo)
    elseif(_group STREQUAL "grpc")
      find_package(gRPC REQUIRED)
    elseif(_group STREQUAL "autoviz")
      find_package(Qt6 REQUIRED COMPONENTS
        Core Gui Widgets OpenGLWidgets OpenGL Xml Svg Network)
    elseif(_group STREQUAL "prometheus")
      find_package(prometheus-cpp CONFIG REQUIRED)
    elseif(_group STREQUAL "sherpa_onnx")
      find_package(SherpaOnnx QUIET)
      if(SherpaOnnx_FOUND)
        message(STATUS "SherpaOnnx found: ${SherpaOnnx_INCLUDE_DIRS}")
      else()
        message(STATUS "SherpaOnnx not found; audio ASR uses stub engine")
      endif()
    elseif(_group STREQUAL "inference")
      if(BUILD_ONNXRUNTIME)
        find_package(OnnxRuntime QUIET)
      endif()
      if(BUILD_TENSORRT)
        find_package(TensorRT QUIET)
        find_package(CUDAToolkit QUIET)
        if(TensorRT_FOUND)
          message(STATUS "TensorRT found: ${TensorRT_INCLUDE_DIRS}")
        else()
          message(STATUS "TensorRT not found; tensorrt backend stubbed")
        endif()
      endif()
    elseif(_group STREQUAL "foxglove")
      find_package(foxglove-sdk CONFIG QUIET)
      if(foxglove-sdk_FOUND)
        find_package(ZLIB REQUIRED)
      endif()
    else()
      message(FATAL_ERROR
        "autonomy_find_dependencies: unknown package group '${_group}'")
    endif()
  endforeach()
endfunction()
