# Super-project build helpers (gz_configure_build / tests).

include_guard(GLOBAL)

function(autonomy_configure_build)
  autonomy_add_proto()
  autonomy_add_modules()
  autonomy_link_umbrella()
endfunction()

function(autonomy_add_proto)
  set(_all ${ALL_PROTO_SRCS} ${ALL_PROTO_HDRS})
  if(BUILD_GRPC)
    list(APPEND _all ${ALL_GRPC_SERVICE_SRCS} ${ALL_GRPC_SERVICE_HDRS})
  endif()
  add_library(autonomy_proto SHARED ${_all})
  target_include_directories(autonomy_proto PUBLIC
    $<BUILD_INTERFACE:${AUTONOMY_WORKSPACE_ROOT}>
    $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}>
    $<INSTALL_INTERFACE:include>)
  target_link_libraries(autonomy_proto PUBLIC
    protobuf::libprotobuf automsgs)
  if(BUILD_GRPC)
    target_link_libraries(autonomy_proto PUBLIC grpc++ grpc)
  endif()
  if(TARGET automsgs_proto_copy)
    add_dependencies(autonomy_proto automsgs_proto_copy)
  endif()
  set_property(GLOBAL APPEND PROPERTY AUTONOMY_MODULE_TARGETS autonomy_proto)
  add_library(autonomy::proto ALIAS autonomy_proto)
endfunction()

function(autonomy_add_modules)
  if(NOT DEFINED AUTONOMY_ENABLED_MODULES)
    message(FATAL_ERROR
      "autonomy_add_modules: compute AUTONOMY_ENABLED_MODULES first")
  endif()
  if(NOT TARGET autonomy)
    add_library(autonomy INTERFACE)
    add_library(autonomy::autonomy ALIAS autonomy)
  endif()
  foreach(_mod IN LISTS AUTONOMY_ENABLED_MODULES)
    if(DEFINED AUTONOMY_MODULE_CONDITION_${_mod})
      # Value is a variable *name* (e.g. BUILD_GRPC or foxglove-sdk_FOUND).
      set(_cond_name "${AUTONOMY_MODULE_CONDITION_${_mod}}")
      if(NOT "${${_cond_name}}")
        message(STATUS "autonomy: skip module '${_mod}' (${_cond_name}=OFF)")
        continue()
      endif()
    endif()
    add_subdirectory(autonomy/${_mod})
  endforeach()
endfunction()

function(autonomy_link_umbrella)
  set(_deps autonomy_proto)
  foreach(_mod IN LISTS AUTONOMY_MODULE_ORDER)
    if(TARGET autonomy_${_mod})
      list(APPEND _deps autonomy_${_mod})
    endif()
  endforeach()
  target_link_libraries(autonomy INTERFACE ${_deps})
  target_include_directories(autonomy INTERFACE
    $<BUILD_INTERFACE:${AUTONOMY_WORKSPACE_ROOT}>
    $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}>
    $<INSTALL_INTERFACE:include>)
endfunction()

function(autonomy_add_tests)
  if(NOT BUILD_TEST)
    return()
  endif()
  set(_test_helper_hdrs "")
  set(_test_helper_srcs "")
  foreach(_mod IN LISTS AUTONOMY_TEST_MODULES)
    list(APPEND _test_helper_hdrs ${AUTONOMY_TEST_HELPER_HDRS_${_mod}})
    list(APPEND _test_helper_srcs ${AUTONOMY_TEST_HELPER_SRCS_${_mod}})
  endforeach()
  list(REMOVE_DUPLICATES _test_helper_hdrs)
  list(REMOVE_DUPLICATES _test_helper_srcs)

  set(TEST_LIB autonomy_test_library)
  if(_test_helper_srcs)
    add_library(${TEST_LIB} ${_test_helper_hdrs} ${_test_helper_srcs})
    target_include_directories(${TEST_LIB} SYSTEM PRIVATE "${GMOCK_INCLUDE_DIRS}")
    target_link_libraries(${TEST_LIB} PUBLIC ${PROJECT_NAME})
  else()
    add_library(${TEST_LIB} INTERFACE)
    if(_test_helper_hdrs)
      target_sources(${TEST_LIB} INTERFACE ${_test_helper_hdrs})
    endif()
    target_include_directories(${TEST_LIB} SYSTEM INTERFACE "${GMOCK_INCLUDE_DIRS}")
    target_link_libraries(${TEST_LIB} INTERFACE ${PROJECT_NAME})
  endif()

  foreach(_mod IN LISTS AUTONOMY_TEST_MODULES)
    foreach(ABS_FIL IN LISTS AUTONOMY_TESTS_${_mod})
      file(RELATIVE_PATH REL_FIL ${PROJECT_SOURCE_DIR} ${ABS_FIL})
      get_filename_component(DIR ${REL_FIL} DIRECTORY)
      get_filename_component(FIL_WE ${REL_FIL} NAME_WE)
      string(REPLACE "/" "." TEST_TARGET_NAME "${DIR}/${FIL_WE}")

      autonomy_test("${TEST_TARGET_NAME}" ${ABS_FIL})
      add_dependencies("${TEST_TARGET_NAME}" ${PROJECT_NAME})
      if(TARGET automsgs)
        add_dependencies("${TEST_TARGET_NAME}" automsgs)
      endif()
      if(BUILD_GRPC)
        target_link_libraries("${TEST_TARGET_NAME}" PUBLIC grpc++ grpc)
      endif()
      if(BUILD_PROMETHEUS)
        target_link_libraries("${TEST_TARGET_NAME}" PUBLIC
          prometheus-cpp-core prometheus-cpp-pull)
      endif()
      target_link_libraries("${TEST_TARGET_NAME}" PUBLIC ${TEST_LIB})
    endforeach()
  endforeach()
endfunction()
