load(
    "//tools:package.bzl",
    "autonomy_cc_library",
)

package(default_visibility = ["//visibility:public"])

autonomy_cc_library(
    name = "autonomy_audio",
    srcs = [
        "audio_component.cpp",
        "common/audio_info.cpp",
        "common/message_process.cpp",
        "inference/asr/asr_engine.cpp",
        "inference/direction_detection.cpp",
        "inference/fft.cpp",
        "inference/moving_detection.cpp",
        "options.cpp",
    ],
    hdrs = [
        "audio_component.hpp",
        "common/audio_info.hpp",
        "common/message_process.hpp",
        "inference/asr/asr_engine.hpp",
        "inference/direction_detection.hpp",
        "inference/fft.hpp",
        "inference/moving_detection.hpp",
        "options.hpp",
    ],
    copts = ['-DMODULE_NAME=\"audio\"'],
    include_prefix = "autonomy/audio",
    deps = [
        "//autonomy/common:autonomy_common",
        "//:automsgs",
        "//:autonomy_headers",
        "@eigen//:eigen",
        "@com_github_google_glog//:glog",
        "@com_google_protobuf//:protobuf",
        "//:pthread",
    ],
)

filegroup(
    name = "runtime_data",
    srcs = glob(
        [
            "conf/**",
            "dag/**",
            "launch/**",
        ],
        allow_empty = True,
    ),
)
