/*
 * Copyright 2025 The Openbot Authors (duyongquan)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <algorithm>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#include <google/protobuf/descriptor.h>
#include <google/protobuf/compiler/code_generator.h>
#include <google/protobuf/io/printer.h>
#include <google/protobuf/io/zero_copy_stream.h>

#include "Generator.hh"

#include <filesystem>
namespace fs = std::filesystem;

namespace google {
namespace protobuf {
namespace compiler {
namespace cpp {

static std::vector<std::string> getNamespaces(const std::string& package) {
  std::vector<std::string> result;
  std::istringstream ss(package);
  std::string item;
  while (std::getline(ss, item, '.'))
    if (!item.empty())
      result.push_back(item);
  return result;
}

Generator::Generator(const std::string& /*name*/) {}

Generator::~Generator() = default;

bool Generator::Generate(const FileDescriptor* file,
                         const std::string& /*parameter*/,
                         GeneratorContext* generator_context,
                         std::string* /*error*/) const {
  fs::path file_path(file->name());
  fs::path parent_path = file_path.parent_path();
  std::string file_stem = file_path.stem().string();

  std::string identifier;
  std::string header_filename;
  std::string detail_header_filename;

  for (const auto& part : parent_path) {
    identifier += part.string() + "_";
    header_filename += part.string() + "/";
    detail_header_filename += part.string() + "/";
  }
  identifier += file_stem;
  header_filename += file_stem + ".am.h";
  detail_header_filename += "details/" + file_stem + ".pb.h";

  // Write .pb_index (one message type name per line)
  std::unique_ptr<io::ZeroCopyOutputStream> index_stream(
      generator_context->Open(identifier + ".pb_index"));
  io::Printer index_printer(index_stream.get(), '$');
  for (int i = 0; i < file->message_type_count(); ++i)
    index_printer.PrintRaw(file->message_type(i)->name() + "\n");

  // Write wrapper header .am.h
  std::map<std::string, std::string> variables;
  variables["filename"] = file->name();
  variables["define_guard"] = identifier;
  variables["detail_header"] = detail_header_filename;

  std::unique_ptr<io::ZeroCopyOutputStream> header_stream(
      generator_context->Open(header_filename));
  io::Printer printer(header_stream.get(), '$');

  printer.Print(variables,
    "// Generated by the automsgs protoc plugin.  DO NOT EDIT!\n"
    "// source: $filename$\n\n"
    "#ifndef $define_guard$\n"
    "#define $define_guard$\n\n"
    "#include <memory>\n\n"
    "#include <automsgs/msgs/Export.hh>\n"
    "#include <$detail_header$>\n\n");

  const std::string& package = file->package();
  auto ns = getNamespaces(package);
  for (const auto& n : ns)
    printer.PrintRaw("namespace " + n + " {\n");

  for (int i = 0; i < file->message_type_count(); ++i) {
    const Descriptor* desc = file->message_type(i);
    const std::string& name = desc->name();
    printer.PrintRaw("typedef std::unique_ptr<" + name + "> " + name + "UniquePtr;\n");
    printer.PrintRaw("typedef std::unique_ptr<const " + name + "> Const" + name + "UniquePtr;\n");
    printer.PrintRaw("typedef std::shared_ptr<" + name + "> " + name + "SharedPtr;\n");
    printer.PrintRaw("typedef std::shared_ptr<const " + name + "> Const" + name + "SharedPtr;\n");
  }

  for (auto it = ns.rbegin(); it != ns.rend(); ++it)
    printer.PrintRaw("}  // namespace " + *it + "\n");
  printer.PrintRaw("\n");
  printer.Print(variables, "#endif  // $define_guard$\n");

  return true;
}

}  // namespace cpp
}  // namespace compiler
}  // namespace protobuf
}  // namespace google
