foxglove:
  host: "0.0.0.0"
  port: 8765

autolink:
  topic_whitelist:
    - ".*"
  min_update_period_ms: 100.0
  max_update_period_ms: 5000.0

mcap:
  enabled: true
  output_path: "autoviz.mcap"
  flush_on_write: false
