# =============================================================================
# Optional Ogre render backend
#
# Resolution order: VENDOR (source) > AUTOVIZ_OGRE_ROOT > system pkg-config.
# Results are stored in CACHE INTERNAL for reuse by Tests.cmake.
# =============================================================================

function(autoviz_apply_ogre_backend _target)
  if(NOT AUTOVIZ_USE_OGRE)
    return()
  endif()

  set(_vendor ${AUTOVIZ_OGRE_VENDOR})
  if(NOT _vendor AND NOT AUTOVIZ_OGRE_ROOT)
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
      pkg_check_modules(_ogre_probe OGRE)
    endif()
    if(AUTOVIZ_OGRE_AUTO_VENDOR AND
       (NOT _ogre_probe_FOUND OR NOT _ogre_probe_VERSION MATCHES "^1\\.12"))
      message(STATUS "System Ogre is not 1.12.x; enabling AUTOVIZ_OGRE_VENDOR")
      set(_vendor ON)
    endif()
  endif()

  if(_vendor)
    message(STATUS "Autoviz: building Ogre 1.12.10 via FetchContent")
    include(FetchContent)
    set(OGRE_BUILD_COMPONENT_BITES OFF CACHE BOOL "" FORCE)
    set(OGRE_BUILD_COMPONENT_PYTHON OFF CACHE BOOL "" FORCE)
    set(OGRE_BUILD_COMPONENT_JAVA OFF CACHE BOOL "" FORCE)
    set(OGRE_BUILD_COMPONENT_CSHARP OFF CACHE BOOL "" FORCE)
    set(OGRE_BUILD_SAMPLES FALSE CACHE BOOL "" FORCE)
    set(OGRE_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(OGRE_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
    set(OGRE_CONFIG_THREADS 0 CACHE STRING "" FORCE)
    set(OGRE_RESOURCEMANAGER_STRICT 2 CACHE STRING "" FORCE)
    set(OGRE_BUILD_RENDERSYSTEM_GL TRUE CACHE BOOL "" FORCE)
    set(OGRE_BUILD_RENDERSYSTEM_D3D11 OFF CACHE BOOL "" FORCE)
    set(OGRE_BUILD_RENDERSYSTEM_D3D9 OFF CACHE BOOL "" FORCE)
    FetchContent_Declare(autoviz_ogre
      GIT_REPOSITORY https://github.com/OGRECave/ogre.git
      GIT_TAG v1.12.10 GIT_SHALLOW TRUE
      PATCH_COMMAND bash "${AUTOVIZ_ROOT}/cmake/apply_ogre_patches.sh" <SOURCE_DIR>)
    FetchContent_MakeAvailable(autoviz_ogre)
    set(_ogre_lib OgreMain)
    set(_ogre_overlay OgreOverlay)
    set(_ogre_includes "${autoviz_ogre_SOURCE_DIR}/OgreMain/include")
    if(EXISTS "${autoviz_ogre_BINARY_DIR}/include")
      list(APPEND _ogre_includes "${autoviz_ogre_BINARY_DIR}/include")
    endif()
    if(OGRE_PLUGINDIR)
      set(_ogre_plugins "${OGRE_PLUGINDIR}")
    endif()
    set(_rviz_media ON)
  elseif(AUTOVIZ_OGRE_ROOT)
    find_path(_inc OGRE/Ogre.h HINTS "${AUTOVIZ_OGRE_ROOT}/include" "${AUTOVIZ_OGRE_ROOT}/include/OGRE")
    find_library(_lib OgreMain HINTS "${AUTOVIZ_OGRE_ROOT}/lib" "${AUTOVIZ_OGRE_ROOT}/lib64")
    find_library(_overlay OgreOverlay HINTS "${AUTOVIZ_OGRE_ROOT}/lib" "${AUTOVIZ_OGRE_ROOT}/lib64")
    if(NOT _inc OR NOT _lib)
      message(FATAL_ERROR "AUTOVIZ_OGRE_ROOT does not contain OgreMain")
    endif()
    set(_ogre_includes "${_inc}")
    set(_ogre_lib "${_lib}")
    set(_ogre_overlay "${_overlay}")
    set(_ogre_plugins "${AUTOVIZ_OGRE_ROOT}/lib/OGRE")
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
      pkg_check_modules(_probe OGRE)
    endif()
    set(_rviz_media OFF)
    if(_probe_FOUND AND _probe_VERSION MATCHES "^1\\.12")
      set(_rviz_media ON)
    endif()
  else()
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(OGRE REQUIRED OGRE)
    pkg_check_modules(OGRE_OVERLAY REQUIRED OGRE-Overlay)
    set(_ogre_lib ${OGRE_LIBRARIES})
    set(_ogre_overlay ${OGRE_OVERLAY_LIBRARIES})
    set(_ogre_includes ${OGRE_INCLUDE_DIRS} ${OGRE_OVERLAY_INCLUDE_DIRS})
    if(OGRE_PLUGINDIR)
      set(_ogre_plugins "${OGRE_PLUGINDIR}")
    endif()
    set(_rviz_media OFF)
    if(OGRE_VERSION MATCHES "^1\\.12")
      set(_rviz_media ON)
    endif()
  endif()

  target_compile_definitions(${_target} PRIVATE AUTOVIZ_USE_OGRE
    AUTOVIZ_OGRE_MEDIA_DIR="${AUTOVIZ_ROOT}/resources/ogre_media")
  if(_rviz_media)
    target_compile_definitions(${_target} PRIVATE AUTOVIZ_OGRE_RVIZ_MEDIA)
    message(STATUS "Point cloud shaders: rviz ogre_media (Ogre 1.12.x)")
  else()
    message(STATUS "Point cloud shaders: stub materials (use -DAUTOVIZ_OGRE_VENDOR=ON for RViz parity)")
  endif()
  if(_ogre_plugins)
    target_compile_definitions(${_target} PRIVATE AUTOVIZ_OGRE_PLUGIN_DIR="${_ogre_plugins}")
  endif()

  target_include_directories(${_target} SYSTEM PRIVATE ${_ogre_includes})
  find_package(Eigen3 REQUIRED)
  target_link_libraries(${_target} PRIVATE ${_ogre_lib} ${_ogre_overlay} Eigen3::Eigen)

  if(_AUTOVIZ_HAS_ASSIMP)
    if(assimp_FOUND)
      target_link_libraries(${_target} PRIVATE assimp::assimp)
    else()
      target_include_directories(${_target} SYSTEM PRIVATE ${ASSIMP_INCLUDE_DIRS})
      target_link_libraries(${_target} PRIVATE ${ASSIMP_LIBRARIES})
    endif()
    target_compile_definitions(${_target} PRIVATE AUTOVIZ_USE_ASSIMP)
  endif()

  set(_AUTOVIZ_OGRE_TARGET "${_ogre_lib}" CACHE INTERNAL "")
  set(_AUTOVIZ_OGRE_OVERLAY_TARGET "${_ogre_overlay}" CACHE INTERNAL "")
  set(_AUTOVIZ_OGRE_INCLUDE_DIRS "${_ogre_includes}" CACHE INTERNAL "")
  set(_AUTOVIZ_OGRE_PLUGIN_DIR "${_ogre_plugins}" CACHE INTERNAL "")
  set(_AUTOVIZ_OGRE_RVIZ_MEDIA "${_rviz_media}" CACHE INTERNAL "")
endfunction()
